backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/listings-importer.ts, backend/core/scripts/minimal-listing.json, backend/core/src/auth/authz_policy.csv, backend/core/src/shared/units-transformations.ts, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/locales/general_OLD.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json
Addresses https://github.com/CityOfDetroit/affordable-housing-app/issues/86
This change updates the listing-import scripts so that all imported listings have all the fields and relationships that the frontend expects. The scripts now create an individual `unit` for each unit referenced by the imported data. For example, if an HRD listing has:
```
"Number_0BR" : 0, 
"Number_1BR" : "50", 
"Number_2BR" : "20", 
"Number_3BR" : "2", 
"Number_4BR" : "0", 
"Number_5BR" : null, 
```
Then the script will create 50 instances of "oneBdrm" units, 20 instances of "twoBdrm" units, and 2 instances of "threeBdrm" units.
Considerations:
- Each unit sets a made-up ami_percentage of 30%. Future work should update this to its actual value.
- This new process of creating an individual unit for every unit …
=> Update the data import scripts so that the imported listings display without errors

Dockerfile.sites-partners, Dockerfile.sites-public
Addresses #100 
The links on the site generated at build time were using `http` instead of `https`, but the runtime variable was using the `https` version of backend/core, which causes mixed content errors. If we generate the site with `https`, everything will be consistent.
Build the production Docker container of the sites/public or sites/partners app and connect to the deployed version of the backend site.
=> Use https in the Dockerfile for the backend site.

sites/public/pages/listings.tsx, sites/public/pages/listings/page/[page].tsx
Addresses #54 
This will allow us to add the Detroit test data to the demo site without
overwhelming the /listings page. Later we can redirect /listings to
/listings/page/1 and add buttons for next and previous pages.
If you have > 10 listings, you can see that the /listings page is limited to 10 and go to `/listings/page/2`, `/listings/page/3`, etc. for more pages.
=> Hardcode the frontend pagination to 10 listings.

backend/core/src/listings/listings.service.ts, backend/core/test/listings/listings.e2e-spec.ts
Addresses #56 and #141 
This change corrects the off-by-one error in `totalPages` in the pagination metadata, and adds tests that confirm that the fix gives the intended result.
```
$ cd backend/core
$ yarn test:e2e:local
```
=> Fix listing pagination off-by-one bug (and add tests to confirm)

sites/public/pages/listings.tsx, ui-components/src/global/vendor/AgPagination.tsx, ui-components/src/global/vendor/ag_grid.scss
Creates an option to pin the pagination UI component to the bottom of the view, and sets this to true for the main listings page.
=> Pin pagination component to bottom of view

.travis.yml
There is apparently a container pull limit and we'd have to
authenticate. We should instead try to use the postgres/redis built in
to Travis linux images to avoid this. Removing the backend/core tests
since those require the database to be set up.
=> Remove the docker services from Travis.

sites/public/pages/listings.tsx, ui-components/src/global/vendor/AgPagination.tsx
Removes the "Items Per Page" and "Jump to Page" components from the pagination UI components.
This makes the paginated listings view more mobile friendly.
Before the change:
After the change:
=> Remove components from pagination

backend/core/src/listings/dto/listing.dto.ts
Addresses #183 
I can't fully explain what this change is doing or why it works. How I arrived at this change: by observing that the `unitsSummarized` field in `ListingDto` was the only field that appeared to be defined by a `get` method; all other derived fields were decorated with the `@Transform` decorator (which the [NestJS documentation](https://docs.nestjs.com/techniques/serialization#transform) is unfortunately quite light on.)
I dug into code that's involved in the serialization and recorded thoughts in https://github.com/CityOfDetroit/bloom/issues/183#issuecomment-885894007. That led to an observation of something being different between our code and Exygy's, but that difference didn't point towards an obvious solution. At that point, I stopped trying to understand the problem …
=> Fix the bug that causes the unit summaries not to show up in the /listings view

CHANGELOG.md, backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/listings.service.ts, backend/core/src/shared/dto/filter.dto.ts, backend/core/src/shared/filter/index.ts
Addresses #258
Moves `WHERE` clauses and pagination to a subquery, so filtered results return all listing data.
Previously, if we filtered on units or preferences, only the units or preferences that match the query were returned. Now, everything about a building that contains matching units is returned
Also:
- The subquery gets a list of matching ids by only joining the tables necessary for filtering, before joining everything together
- Fixes a bug where `meta.totalItems` was the total number of listings, not the total number of listings that match the filters
- Refactors pagination logic to use the same subquery as the filters
- Updates tests to match, and test `meta` details
- Moves sorting logic back into the query ([this comment](https://github.com/CityOfDetroit/affordable-housing-app …
=> Move where clauses and pagination to subquery, so filtered results return all listing data

backend/core/scripts/listings-importer.ts
Just a quick fix to the `listings-importer.ts` library to account for the change from `unitType` being a string in the `units` table to `unitType` being its own separate entity (in a separate table in the DB).
Before this change: `import-listing-from-json-file.ts` with input `minimal-listing.json` failed with "unitType.nested property unitType must be either object or array".
With this change: `import-listing-from-json-file.ts` with input `minimal-listing.json` succeeds.
=> Update listings-importer library to match new unitType storage details

backend/core/scripts/listings-importer.ts, backend/core/scripts/minimal-listing.json
This change removes fields from `minimal-listing.json` that were previously required but are no longer required. This keeps `minimal-listing.json` up-to-date and representative of the minimal set of fields that are required to be populated for the backend and frontend to accept and handle gracefully.
Check: with this change, I was able to run `import-listing-from-json-file` with this new `minimal-listing.json` and (a) the backend accepted it, (b) `localhost:3000/listings` rendered without errors, and (c) the listing detail page (`localhost:3000/listing/{id}`) rendered without errors.
=> Trim minimal listing json

sites/partners/styles/overrides.scss, sites/public/styles/overrides.scss
#221 
Overrides button hover styles.
Because the Detroit color palette doesn't differentiate between "dark" and "darker" background colors, there was no noticeable difference in hover styles for primary buttons. This change overrides the hover color to be lighter, and changes the text color to black.
Examples:
There are examples of primary buttons in the public sign-in page, eligibility welcome page, and listing details page.
=> Override primary button hover styles

backend/core/src/auth/authz_policy.csv, backend/core/test/authz/authz.e2e-spec.ts, sites/partners/src/listings/PaperListingForm/sections/Preferences.tsx
#306 
Allows non-admins to pull listing preference data.
Also makes the preference page more resilient to failures by avoiding an infinite rendering loop if there's an error fetching preferences, and failing to load if there's an error.
Log in as a non-admin and try to edit listing preferenes. Notice how the page doesn't freeze. :)
=> Allow non-admin to access preferences

.travis.yml
This way, if the first stage tests fail, the entire run will fail and
free up Travis resources for other PRs. It does add an extra ~6 minutes
of time in the golden case, but will hopefully prevent bottlenecks that
add ~30 minutes to other PRs.
Addresses aspects of #163.
=> Run the longer tests in a second stage.

CHANGELOG.md, backend/core/src/listings/listings.service.spec.ts, backend/core/src/shared/dto/filter.dto.ts, backend/core/src/shared/filter/index.ts
Add support for IN comparison for lists
Addresses #255 
Add support for commas-separated lists to filters. Also ensures that provided comparison is valid.
- Adds an `IN` comparison type
- If the filter specifies an `IN` comparison, treat the filter value as a comma-separated list
- Handles if there are extra commas and spaces between the commas and the value
- Add tests to listings service spec. (We should also start writing tests for the addFilters code itself)
- Adds switch statement to `addFilters()` to ensure that the provided comparison is a valid one
=> Add support for comma-separated lists to filter and ensure comparisons are valid

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, backend/core/src/applications/applications.service.ts, backend/core/src/shared/dto/pagination.dto.ts
Addresses #192 
In https://github.com/bloom-housing/bloom/pull/1578 we added a new PaginationAllowsAllQueryParams params type for listings. Now we can revert the changes we made to the query params defaults in https://github.com/CityOfDetroit/bloom/pull/133
=> Revert pagination defaults to upstream

backend/core/src/listings/entities/listing.entity.ts, backend/core/src/migration/1628017712683-addListingAndPropertyFields.ts
This change corrects the type for `amiPercentageMin` and `amiPercentageMax`; they should be `integer`s, not `text`. https://github.com/CityOfDetroit/bloom/pull/311 erroneously added these fields as strings. Since this is a small change, I've opted to modify the previous DB migration instead of creating a whole new DB migration.
I did two things:
1. Ran `yarn db:reseed` with the new DB migration and inspected the listings table (`\d listings;`) to verify that the type of `ami_percentage_min` and `ami_percentage_max` are `integer`.
2. I temporarily modified `minimal-listing.json` to include an integer for `amiPercentageMin`, and I verified that uploading that listing was successful.
=> Fix the type of amiPercentage(Min|Max)

backend/core/src/seed.ts, backend/core/test/listings/listings.e2e-spec.ts
Closes #369
Hardcodes the length of the list for the pagination calls to avoid flakiness in the backend e2e tests.
backend/core e2e tests were flaky prior to this; after this they were no longer flaky
=> Hardcode the number of items in listings.e2e-spec.ts.

backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/listings-importer.ts, backend/core/src/migration/1625825502154-refactor-unit-types-rent-types-and-priority-types.ts
This change pulls the `createUnitsArray` function out of the "read from ArcGIS" script and into the `listings-importer.ts` library, so that it can be reused for the forthcoming "import from CSV" script. It also removes the fake values it set for fields like `units.amiPercentage` and `units.amiChart` (which were previously required).
This change also changes `uploadListing` to pass a sanitized error message up, rather than killing the process itself. Pushing the error-handling responsibility to the callers allows them to decide whether they'd like to continue uploading more listings even if one fails.
=> Refactor listings-importer library

backend/core/test/listings/listings.e2e-spec.ts
Removes the randomness associated with the default pagination limit of 10 items, since we now have 12 items in the seeds.
=> Fix the flakiness in the backend e2e test.

backend/core/src/seeder/seeder.module.ts, backend/core/src/seeds/listings/listing-default-seed.ts, backend/core/src/seeds/listings/listing-detroit-10145.ts, backend/core/src/seeds/listings/listing-detroit-10147.ts, backend/core/src/seeds/listings/listing-detroit-10157.ts, backend/core/src/seeds/listings/listing-detroit-10158.ts, backend/core/src/seeds/listings/listing-detroit-treymore.ts
Addresses #380 
Creates UnitsSummaryDTOs from the seed files and populates the unit_summary table. Note the monthly rent field is currently a placeholder of $0.
Run your local version and do a db:reseed.  Then open the unit_summary table with `psql bloom` and see that it is populated with data. You should see 12 rows based on the seeded data.
=> Create Units Summary table from seeds

sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailListingPhoto.tsx, sites/public/src/ListingView.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/locales/vi.json, ui-components/src/locales/zh.json
Addresses #330 
Verifies that the listing has any "Features" data. If not, displays a warning that no data is available. E.g:
I manually deleted data from the seeded DB so there were no units or feature information and verified that the warning was displayed and no sections were visible (see photo above).
=> Hide sections and display warning if no features data is available

sites/public/pages/listings.tsx, ui-components/src/overlays/Modal.tsx
Addresses #412
Enables the close button and clicking outside the modal to close it.
Also removes the footer that doesn't contain anything in it. This will
help bring the filter modal closer to the mocks and enable a workaround
for #412.
View the filter modal and click outside the window or the `x` to see that it closes.
=> Enable closing filter modal.

sites/public/styles/overrides.scss, ui-components/src/overlays/Modal.scss
Closes #412 
This change sets the max height of all modals to 80% of the viewport height. And if the modal's height exceeds that max height, it makes it so that the user can scroll up and down within the modal.
Filter modal on desktop view:
Filter modal on mobile view:
Note: I chose 80% of the viewport height instead of 100% because it "felt right" for the modal to not occupy the entire vertical height of the viewport. If anyone has a more evidence-based way to make this decision, please let me know 😅 
Another note: this will affect all views that use the `Modal` React component. I believe the filter modal is the tallest, though, and so is the most likely to run into these max height limits.
I looked at the filter modal in the `/listings` view in both:
=> Constrain the height of the `Modal` component, and make it scrollable if it overflows

sites/public/pages/index.tsx, sites/public/pages/listings.tsx
- Closes #179
Remove the static props that are unused from the page, since on dev builds it will generate those every page load, which slows down the front page load.
Also changes the text on the listings page from "Total Applications" to "Total Listings".
Passing tests, load the front page in a dev build and notice that it's faster.
=> Remove the /listings query from the public front page.

backend/core/src/translations/translations.service.ts
We don't have a Google Translate API key right now, so we can't use the `translateListing` method in `translationService`. When attempting to get a listing in a different language, the `backend/core` will return a 500. This adds an environment variable such that it will be disabled for us. I will also contribute this upstream.
=> Disable Google translate since we don't have API keys.

sites/public/cypress/integration/eligibility-questionnaire.ts
- Addresses #219 
This change adds two Cypress tests for the Eligibility Questionnaire:
- The first verifies that users can access the questionnaire by clicking "Check My Eligibility" on the homepage
- The second verifies that users can navigate through the entire questionnaire flow
```
$ cd sites/public
$ yarn test:headless
```
=> Add Cypress tests for the Eligibility Questionnaire

sites/public/pages/listings.tsx
- Addresses #429
Allow the empty string in the zipcode field, which will clear the zipcode filter.
Start the frontend, filter on zipcodes, and then remove the text from the zipcode field and apply.
=> Initial changes to accept empty strings

sites/public/src/ListingView.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #350
Adds the Region field to the Features details on a listing page.  Only appears when the data is present.
Load any Region data for a listing and view the Features box.
=> Add Region field to listing details

sites/public/src/ListingView.tsx
The details page would fail to render if the listing did not have a unitsSummarized. This passes it optionally. Fixes the currently broken deployment.
=> Fix undefined unitsSummarized property.

sites/public/src/ListingView.tsx, ui-components/src/page_components/listing/ListingsList.tsx
- Addresses #347
Copy the logic from `ListingsList`: if we have `listing.unitsSummary`, let's use that to populate our units table. If we don't, fall back on the existing logic: use `listing.unitsSummarized` if present.
Before:
After:
Run the app and navigate to any listing's individual-listing view.
=> Update `ListingView` to read from `UnitsSummary` (if present)

sites/public/src/ListingView.tsx, ui-components/src/helpers/tableSummaries.tsx
- Addresses #347
This change removes the "total count" column from the unit summary table in the individual-listing view. It also removes everything related to `totalCount` in the shared `getSummariesTableFromUnitsSummary` since the only other component that uses that function (`ListingsList`) already doesn't display "total count".
Note: we've gone back and forth on whether or not to include "total count". I'm sending this PR based on https://github.com/CityOfDetroit/bloom/pull/460#issuecomment-905625330.
Before:
After:
Run the app and navigate to any listing's individual-listing view.
=> Remove the "Total Count" column from the units summary table in `ListingView`

sites/public/src/ListingView.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Addresses #231 
On a listing page view, this change shows the Accessibility section under Features.  If there is no accessibility information available for the listing, it will display a default "Contact property manager" message.
View a listing page and look under the Features section for Accessibility.
=> Show Accessibility details or default message

backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/listings.service.spec.ts, backend/core/src/shared/filter/custom_filters.ts, backend/core/src/shared/filter/index.ts
- Closes #524 
- Addresses #524 
We were casting integer fields to text before using a `>=` comparison, which does a lexicographic comparison instead of a numeric one. This would cause problems when comparing values like "30" and "1400" as text. The "30" would be "larger" because 3 comes after 1.
- Removes cast for the availability filter and when the comparison is `>=`.
- Moves the database fields for the availability filter uses out of the map, for simplicity.
- I did not add tests for this.
=> Stop casting integer field to text in query

backend/core/src/listings/listings.service.ts, backend/core/src/units/dto/unit.dto.ts, sites/partners/lib/helpers.ts, sites/partners/src/listings/PaperListingForm/index.tsx
Fixes issues with adding / editing listings. Some issues were caused by missing data, which needed to be handled more gracefully. Others were just bugs in handling form data.
Go to the partner portal and try to add a new unit to a listing, or add a new listing. You should be able to do this successfully. One catch: make sure you've provided a leasing agent email. Some of our seed don't have them, and this causes the workflow to fail.
NOTE: the one case I've found where this is not true is if you're adding a new listing that contains units in the first publishing. This bug exists upstream too. I filed a ticket [here](https://github.com/bloom-housing/bloom/issues/1790).
=> Fix issues with adding/editing listing

backend/core/src/migration/1630699221778-change-ami-percentage-to-integer.ts, backend/core/src/units-summary/entities/units-summary.entity.ts, backend/core/types/src/backend-swagger.ts
Addresses #478
Migrate the amiPercentage column on the unit summary table to an integer, so we can filter based on it.
Ran the tests and built the site
=> Migrate unitSummary amiPercentage column to int

backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/listings.service.ts
- Closes #530 
Migrates existing filters to query the units summary table and not the units table.
Removes the units table join from the filter query.
Start the backend locally and run:
`http://localhost:3100/listings?page=1&limit=10&filter[$comparison]=%3E=&filter[bedrooms]=1&filter[$comparison]=%3C=&filter[maxRent]=600`
This previously would have mistakenly returned one listing, but now correctly returns no listings.
=> Migrate filters to use units summary

backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/listings.service.ts, backend/core/test/listings/listings.e2e-spec.ts
- Addresses #193
The full listings query returns at least one row per (listing, unit summary) pair, but before this change we didn't enforce any order for unit summary's within a single listing. The result was that the unit summary table in the listings page displayed unit types out of order:
With this change, the backend returns unitSummary's in order (per listing), and the frontend reflects the fix:
Note: this `ORDER BY` clause is only being added to the full query (not the `innerFilteredQuery`) because the purpose of the `innerFilteredQuery` is just to return a bunch of listing IDs, and there are no unit summaries returned by that query.
Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your …
=> Fix the ordering of unit summaries returned by `GET /listings`

sites/public/pages/listings.tsx
- Closes #429
Changes the error check to use the name of the `Field` instead of the id. The errors were there and preventing the submission of the form, but they weren't being displayed because the error variable was being checked for the wrong property.
Try to enter an incorrect value into the filter and see the error message being displayed.
=> Add error message display in the zipcode filter.

backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/types/listing-filter-keys-enum.ts, backend/core/types/src/backend-swagger.ts, sites/public/pages/listings.tsx, ui-components/__tests__/helpers/filters.test.ts, ui-components/src/helpers/filters.ts
Closes Issue #537 
Removes the neighborhood filter from FE and BE
Existing unit tests.
=> Remove neighborhood filter

sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx
Fixes a bug where the radio button to toggle between summaries / individual units in the partner portal wouldn't have a default selection.
Edit a listing in the partner portal and see the default selected item.
=> Fix default radio option for partners summary vs units view

backend/core/src/units-summary/entities/units-summary.entity.ts, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx
- Closes #576 
Fixes the following issues:
- Incorrect validation of min/max rent fields (validating a number as a string) was causing failures when submitting listing edits
- AMI % was being saved as a string when it's a number in the database
- The `Sq Feet` column in the partner view of UnitsSummaries had a "$" prefix
Navigate to the partner portal and add a summary with min/max rent.
=> Fix errors in listing edit form

sites/public/pages/listings.tsx, sites/public/styles/overrides.scss
- Closes #486 
Adds a loading overlay to the listings page while the listings are being loaded.
The data usually loads too quickly to see the spinner. If you want to view it, go to `sites/public/lib/hooks` `useListingsData()` and change `listingsLoading: true`.
=> Add loading indicator on listings page

sites/public/src/ListingView.tsx
- Closes # (issue)
- Addresses #525 
This change updates the size of the "View on Map" link from XS to XL.
Open an individual listing and view the map link size.
=> Change "View on Map" link font size

sites/public/layouts/application.tsx, sites/public/tailwind.config.js
- Closes #220 
Removes feedback link and message in the header on all pages
View the homepage and run a Lighthouse test for accessibility.  Header banner no longer is flagged for contrast.
=> Remove Feedback banner

CHANGELOG.md, sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx, sites/public/pages/listings.tsx, sites/public/src/ListingView.tsx, ui-components/src/helpers/tableSummaries.tsx
- Closes #554 
Removes minimum income from a few places:
- Partner portal listing add / edit forms
- Summary table in main listings view
- Summary table in individual listing view
In the main view summary tables, I replaced the column with an Availability column, because it was easy to hook up and is the column we already display in the individual listing view.
Partner form before:
After:
New summary table in mobile and desktop:
=> Remove minimum income from FE tables/forms

.travis.yml
In #593 I noticed that building the production site actually sped up the overall time for Cypress tests in Travis because the production site responds faster (see the difference between the partner Cypress tests with production build and the public Cypress tests with dev build [here](https://app.travis-ci.com/github/CityOfDetroit/bloom/builds/238135030)). So, apply the same to the public site.
=> Build the production site for Cypress tests.

sites/public/pages/index.tsx, ui-components/src/global/homepage.scss
- Closes #522 
Updated the font size for Eligibility portal on home page.  Adjustment keeps accessibility header levels in place, and simply fixes font size.
BEFORE:
AFTER:
Visit homepage
=> Adjust Eligibility font size on homepage

ui-components/src/navigation/ProgressNav.tsx
- Closes #442 
Disables the default `href` behavior in the nav bar, which is move relevantly used in the eligibility questionnaire. This prevents the url from being appended with a `#` when clicking on a nav link, which caused a user to have to click "back" twice if they wanted to navigate back (once to lose the trailing `#`, and a second time to get back to the previous page).
Example of clicking a nav link and not getting an appended `#`:
Go to the eligibility questionnaire, click through past the "welcome" tab, then click on a prior nav tab. The url should not have a trailing `#`, and clicking the back button should work on the first click.
=> Disable default href behavior in nav bar

sites/public/styles/overrides.scss
Before:
After:
But on mobile (or for narrow window widths), it will still do inconsistent spacing so that each navbar item gets space according to how wide the text is:
AFAICT our codebase only uses the `ProgressNav` for the eligibility questionnaire, so the entirety of this change should be displayed in those screenshots above.
=> Fix the inconsistent spacing between navbar items

CHANGELOG.md, package.json, sites/partners/package.json, sites/public/package.json, sites/public/pages/_app.tsx, sites/public/pages/listings.tsx, sites/public/tailwind.config.js, ui-components/package.json, ui-components/tailwind.config.js, yarn.lock
- Closes #495
Adds the `tailwindcss-rtl` plugin to be able to use `start` and `end` styles instead of left/right. Automatically switches the direction of the app based on the locale.
Viewed the site and swapped between different languages. Fixes for RTL mode will be made in other PRs.
=> Add RTL plugin.

sites/public/lib/hooks.ts, sites/public/pages/eligibility/income.tsx, sites/public/pages/listings.tsx, ui-components/__tests__/helpers/filters.test.ts, ui-components/src/helpers/filters.ts
- Closes #625 
To unblock #581, we need to be able to set a frontend query param like `includeNulls`. This isn't a filter type, or a field on `ListingFilterParams`, so trying to use the backend `ListingFilterParams` to store frontend state doesn't work.
This does the minimal work necessary to decouple the frontend filter state storage from  `ListingFilterParams`, drawing on @elenm's work in #484 and my experiments in #545.
As of this PR, the concept of "what a filter is" is spread across multiple places:
- getComparisonForFilter()
- ListingFilterState
- FrontendListingFilterStateKeys
- ListingFilterKeys
- the encode/decode methods
- the various enums with options for the filters
It could be worth unifying this into a ListingFilterStateManager class that can hold all this in one place. …
=> Decouple frontend filter state storage from ListingFilterParams

sites/partners/lib/helpers.ts, sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx
- Closes #586 
Fixes a bug where legacy `minimumIncomeMin` was causing the Rent Type selector in the units summary form to always default to "Fixed Amount".
Also added income % to the "Rent" column in the summary table. Previously, only fixed rent amounts were showing here. Here is an example of both formats with the changes applied:
Create a new summary with rent type "% of Income" and save. Open the form to edit the summary you just created and see that the "% of Income" radio is selected by default.
=> Fix default rent type bug

backend/core/src/shared/filter/index.spec.ts, backend/core/src/shared/filter/index.ts
- Closes #574
We were `return`ing from `addFilters()` after adding a custom filter, instead of `continue`ing the for loop with the next filter.
Relatedly, if a unit has no availability, we show "waitlist" in the summary. That is misleading, since a unit could show "waitlist" when the building waitlist is not open. That is done here:
https://github.com/CityOfDetroit/bloom/blob/6e91c9231bad636bfbf690845cb01dd4d0bdf210/ui-components/src/helpers/tableSummaries.tsx#L51-L61
cc @willrlin 
Try adding a custom filter, and see that it only further refines the results, instead of ignoring other filters.
=> Fix other filters are ignored when custom filters are applied

sites/public/pages/listings.tsx, ui-components/src/helpers/filters.ts
- Closes #637
A few small fixes I noticed from the deployed site:
- Filter reset button doesn't work - pass in the empty object instead of null.
- includeNulls was able to be set as an empty string in the URL, which would result in it existing as an array in the filter params - check that the value of the filter is not falsey before encoding it into the ListingFilterState object.
- Default value on the Senior Housing filter was not getting set - the default was being set to the ADA filter.
View the site and play with the filter modal.
=> Fix filter reset

backend/core/scripts/import-helpers.ts
- Closes #400
This change makes it so that (if a listing specifies a `managementWebsite`) that listing will only be successfully uploaded if `managementWebsite` is a well-formed URL. (Otherwise we'll note the error and move on to the next listing.)
For what qualifies as a "well-formed URL", I defer to whatever checks happen in the [Javascript URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). One thing to note: "www.google.com" is considered invalid, whereas "http://www.google.com" is considered valid; as a result, the validation added in this change checks for a missing "http://" and adds it if needed. (We are already checking for the missing "http://" in the frontend, https://github.com/CityOfDetroit/bloom/blob/7ec1509e59ff6ffa27213fb4806cb0ec4607ace3/ui-componen …
=> Validate the `listing.managementWebsite` url in the import script

ui-components/src/global/vendor/AgPagination.tsx
- Addresses #313
This change adds "Page X of Y" at the bottom of the listings list page.
Desktop:
Mobile:
It also:
- Makes the `quantityLabel` (e.g. "Total Listings") a required field because simply putting "75" (the number of listings) with no unit would be weird.
- Makes the "Page X of Y" text bold, and leaves the "total listings" text as-is, to more easily visually distinguish them
=> Indicate which page of listings we're on

backend/core/src/shared/filter/custom_filters.ts, backend/core/src/shared/filter/index.ts
- Closes # (issue)
- Addresses # Filtering unknowns with Senior Housing
Including unknown information doesn't make sense for the senior housing filter, so this change reverts the filter back to the prior state before includeNulls was introduced.
Filter by senior housing.
=> Revert senior housing filters to exclude includeNulls

ui-components/src/global/vendor/AgPagination.tsx
- Addresses #313
Before this change, when there are zero items to display, the pagination bar would say "Page 1 of 0":
This change makes it so the pagination bar detects when there are no items to display, and removes the "Page X of Y" altogether:
I checked the listings pagination on both the public and partners sites, in desktop and mobile views.
=> Fix pagination bar when there are zero items

backend/core/scripts/detroit-helpers.ts, backend/core/scripts/import-helpers.ts, backend/core/scripts/import-listing-from-json-file.ts, backend/core/scripts/import-listings-from-csv.ts, backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/minimal-listing.json
- Closes #384
This change removes jurisdiction-lookup logic from `detroit-helpers.ts` and instead uses the jurisdiction-lookup logic that already exists in Exygy's version of `import-helpers.ts`. This (a) brings our import script in sync with Exygy's and (b) allows us to get rid of some verbose code.
There are also a few other one-line changes to bring our listing import script up to date with Exygy's.
I ran each of the three import scripts and verified that they each worked successfully (esp wrt getting the correct jurisdiction).
To verify that this brings us in sync with Exygy, I used a diff tool to check for diffs between their and our versions of the files touched in this PR. (The only remaining diffs are "real" diffs: e.g. "Detroit" instead of "Alameda" in `minimal-listing.json`.)
=> Bring our listing import scripts more in sync with Exygy's

backend/core/src/auth/dto/user-profile.dto.ts, backend/core/test/user/user.e2e-spec.ts
This commit also adds the phoneNumber field to UserProfileUpdateDto.
The upstream merge changed how the user endpoints behave, and broke the test I wrote for verifying a user can change their phone number.
`cd backend/core && yarn test:e2e:local --testPathPattern user.e2e-spec`
=> Fix user E2E tests.

backend/core/scripts/import-listings-from-csv.ts
- Closes #673
This change updates the CSV listing importer so that it reads the neighborhood field from the HRD spreadsheet and uses that to populate the neighborhood field for a listing (which can take any string value).
I ran the CSV listing importer with this change and verified that the DB was updated so that the `property` table had a neighborhood in each newly added row.
=> Import neighborhood field

sites/public/pages/listings/filtered.tsx
- Addresses #692
I missed one spot for updating this string, in the filtered listings page.
Before:
After:
Go to listings, apply a filter.
=> Update filtered listings qualification button text.

sites/public/lib/HorizontalScrollSection.tsx, ui-components/src/actions/Button.tsx, ui-components/src/icons/Icon.tsx
Adds aria labels to the left and right scroll buttons and adds aria-hidden to the section icons since those are only visual decoration.
Inspect html on homepage or use a screenreader to navigate
=> Add aria labels to HorizontalScrollSection

backend/core/src/application-flagged-sets/application-flagged-sets.service.ts, backend/core/src/auth/dto/user-basic.dto.ts, backend/core/src/auth/dto/user-profile.dto.ts, backend/core/src/auth/dto/user.dto.ts, backend/core/src/auth/entities/user.entity.ts, backend/core/src/auth/services/user.service.ts, backend/core/src/migration/1636490631999-add-user-preferences.ts, backend/core/src/user-preferences/dto/user-preferences.dto.ts, backend/core/src/user-preferences/entities/user-preferences.entity.ts, backend/core/types/src/backend-swagger.ts
- Closes #747
This adds a UserPreferences table, keyed on user id. Two notification preferences are initially added to the table.
1. Go to swagger docs
2. Log in as test@example.com
3. GET `user/`
4. PUT `userProfile/`, setting `{"sendEmailNotifications": true}` for the `preferences` key
5. GET `user/` again, verify that `preferences is set
=> feat: add user preferences table

backend/core/src/listings/dto/filter-type-to-field-map.ts, backend/core/test/listings/listings.e2e-spec.ts
- Closes #759
The "bedrooms" filter type had been mis-mapped to a field after the most recent upstream merge.
Navigate to listings and apply a bedroom filter. OR:
`cd backend/core && yarn test:e2e:local --testPathPattern listings.e2e-spec --testNamePattern "Unit size filtering"`
=> fix: filtering on bedroom count

sites/public/styles/overrides.scss
Carves out a medium screen size that left aligns the title so that we can have more links on the right side without overlapping the logo. The xl screen size is unchanged. This unblocks adding more pages to the header.
View site at medium size (between 768px and 1280px)
=> Tweak header css at medium screen size

sites/partners/pages/unauthorized.tsx, sites/public/pages/account/application/[id].tsx, sites/public/pages/create-account.tsx
I kept seeing warnings in the logs about these preventing Fast Refresh from preserving local component state. 
Run `yarn dev:public`, and observe no more pesky logs.
=> fix: remove anonymous arrow functions

backend/core/src/listings/dto/listing-filter-params.ts, backend/core/types/src/backend-swagger.ts, sites/public/src/forms/filters/FilterForm.tsx, sites/public/styles/overrides.scss, ui-components/__tests__/helpers/filters.test.ts, ui-components/src/helpers/filters.ts, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #752
This switched the unit size filter from a selector, to a set of checkboxes. Supporting the backend query is achieved by switching the `bedrooms` filter parameter from a number to a string, and switching the comparison from `>=` to `IN`. The frontend coalesces all the checkboxes to construct the `bedrooms` backend filter value. E.g. if "0" and "3" are checked, then `bedrooms="0,3"` is sent to the backend.
Desktop:
Mobile:
Go to filter modal, check "0" and "3", verify that only listings containing 0 or 3 bedrooms are returned.
=> feat: update unit size filter

backend/core/src/detroit-seed.ts, backend/core/src/seeder/seeder.module.ts, backend/core/src/seeds/listings/listing-detroit-10202.ts
- Addresses #790
To test updating this listing from imported XML, we need an initial listing. Data is populated from the information in the HRD spreadsheet.
`cd backend/core && yarn db:reseed:detroit`
=> chore: create River Towers seed listing

backend/core/src/listings/entities/listing.entity.ts, backend/core/src/listings/listings.service.ts, backend/core/src/property/entities/property.entity.ts, backend/core/src/shared/units-transformations.ts
- Addresses #800
It seems the query builder logic doesn't return lists of the specified entity type, so it's necessary to map the returned query result to the entity type. Otherwise, `get` accessors don't work, since those are only defined on the entity type, and not on the generic objects that the query returns.
Seed the db with Detroit listings, then find the "New Center Square" listing card. It should say "Open Waitlist" in the card:
=> fix: pass waitlist + other info from backend

backend/core/scripts/import-listings-from-csv.ts, backend/core/src/listings/dto/listing-published-create.dto.ts
- Closes #779
In order for a listing to be active, there are more required fields. This commit adds these required fields, and relaxes one of the requirements on the "units" field.
Get an example `csv` file to import, and then
```cd backend/core && yarn ts-node scripts/import-listings-from-csv.ts http://localhost:3100 admin@example.com:abcdef example.csv```
=> fix: import HRD csv data

ui-components/src/global/forms.scss
Fixes the rtl styles for checkboxes by changing margin-left/margin-right to margin-inline-start/margin-inline-end
=> Fix checkbox rtl style

sites/public/layouts/Eligibility.module.scss, sites/public/layouts/eligibility.tsx, sites/public/pages/eligibility/age.tsx, sites/public/pages/eligibility/disability.tsx, sites/public/pages/eligibility/disclaimer.tsx, sites/public/pages/eligibility/household.tsx, sites/public/pages/eligibility/income.tsx, sites/public/pages/eligibility/welcome.tsx, sites/public/styles/overrides.scss, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #828
This PR tweaks the layout and styling of the eligibility questionnaire header.
Start the eligibility questionnaire.
=> fix: update eligibility questionnaire header

sites/public/styles/overrides.scss
- Closes #829
This PR tweaks the styling on the questionnaire stepper to match the [mocks](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=3540%3A13497).
Navigate to the eligibility questionnaire.
=> fix: update questionnaire stepper styling

backend/core/src/listings/dto/filter-type-to-field-map.ts, backend/core/src/listings/dto/listing-filter-params.ts, backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/types/listing-filter-keys-enum.ts, backend/core/test/listings/listings.e2e-spec.ts, backend/core/types/src/backend-swagger.ts, ui-components/src/helpers/filters.ts
- Addresses #814
This commit adds a "neighborhood" key to the list of supported filters, and hooks it up to the property.neighborhood field of listings in the database.
Navigate to http://localhost:3000/listings/filtered?page=1&neighborhood=Forest%20Park,%20Elmwood%20Park in a local build. You should see two results show up, one from each neighborhood specified in the URL.
=> feat: support neighborhood filter on backend

sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/helpers/filters.ts, ui-components/src/helpers/regionNeighborhoodMap.ts
- Closes #814 
This commit connects the region filter UI with an actual backend filter.
Open the filter dialog, select "Eastside". You should observe 5 listings from those neighborhoods appear in the results.
=> feat: hook up region filter

sites/public/src/forms/filters/FilterForm.tsx, sites/public/styles/overrides.scss
- Closes #825
Changes the bedroom filters to be 2 columns. Changes the 2 column css to use flex instead of column-count for more responsiveness and to get away from floats (column-count is older and float based which can cause issues). Also fix the filter height on desktop.
=> Make bedroom filters 2 columns and fix filter styles

sites/public/src/ListingView.tsx
- Closes #596
Adds the neighborhood to the right rail. Also makes the right-rail not 100% height and removes the duplicate Apply Online button.
=> Add neighborhood info to right rail

sites/public/pages/index.tsx, ui-components/src/helpers/regionNeighborhoodMap.ts
- Closes #815
This commit implements navigating to the correct filter when a region card is clicked on the home page.
Click on the "Eastside" region button, observe the correct filtered URL.
=> feat: connect region cards on homepage to filter

backend/core/src/listings/listings-notifications.ts, backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/listings.service.ts
- Addresses #705 
This change adds a hook to the update-listing flow to trigger an asynchronous process to send notifications about the updated listing to all users who are opted-in for SMS alerts. The notifications are only sent if the listing's status changes from "anything other than active" to "active".
Note: this change simplifies the implementation of `sendListingNotifications`: we now send the same new-listing notification regardless of whether we're dealing with a newly created-listing or a listing that was just updated to be "active". From the user's perspective, they're equivalent (the listing wasn't showing up on the site; now it is).
`cd backend/core && yarn test`
=> Add support for sending new-listing notifications to opted-in users when a listing's status is updated from not-active to active

sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx, sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx, sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx, sites/partners/src/listings/PaperListingForm/sections/Units.tsx
Closes #970
- Closes #970
Removes "Required to publish" labels below a couple of fields.
Open a partners portal and check "Required to publish" labels visibility. They should be visible below following fields only:
- Jurisdiction
- Listing Name
=> refactor: Remove required to publish labels

shared-helpers/src/formKeys.ts, sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx, sites/public/src/ListingView.tsx, ui-components/src/locales/general.json
- Closes #1028 
Add hearing, mobility, visual to the accessibility building features (checkbox set)
Rename the existing a11y text field to `Additional Accessibility`
Remove the default text on the `Additional Accessibility` field (`Contact property management`) so that it does not show at all if nothing was entered
Check partners for the 3 new checkboxes in a11y features on edit and details
Check public for the new bullets, and add/remove the a11y textbox and ensure it adds/removes and has the new header
=> fix: add hearing mobility visual to a11y features

sites/public/src/ListingView.tsx
Hide maximum income blurb and link if there is no HMI table / data available amongst the unit groups
Create a unit group with no AMI levels, no text should show
Create a unit group with enough AMI info to render the table (an ami chart, ami percentage, and occupancy range), text should show
=> fix: hide hmi link if no hmi table

backend/core/src/shared/units-transformations.ts
This fixes when rent range was empty on a 
Best way to verify this:
create or edit a listing
add a unit group, and add ami levels but do not add a rent to the ami level
save the listing
view the preview (or take a look at it on the public site)
under `RENT` on the table, it should be empty
=> fix: fix for when rent range was empty

sites/public/src/ListingView.tsx, ui-components/src/page_components/listing/AdditionalFees.tsx, ui-components/src/text/Description.scss
Fixes: More padding to the right of neighborhood, aligning text content of features with the title, padding on top of additional fees
=> fix: styling issues in features section

sites/public/pages/preview/listings/[id].tsx, ui-components/src/notifications/AlertBox.scss, ui-components/src/notifications/AlertBox.tsx
Brings over the preview alert box fixes from core
Look at a preview listing, you can also check existing alert boxes by trying to visit /user without being signed in
=> fix: preview close alert style fixes

sites/public/src/ListingView.tsx
Create a listing with a unit group with occupancy and no programs, there should be no stray zero
=> fix: stray zero if no programs

backend/core/src/auth/services/user.service.ts
This resolves the pagination issue that has plagued the detroit user grid
the cause of the issue turned out to be the following: https://stackoverflow.com/questions/30038587/how-does-postgres-order-the-results-when-order-by-is-not-provided#:~:text=If%20no%20order%20by%20clause,or%20directly%20from%20the%20table).
basically that postgres when no order by is given returns records in the order it got them. Which could cause a mismatch across pages of data as each page is fetched in isolation. Adding the ORDER BYs thus enforces a consistent ordering and avoids the problem
aim your local at live/dev detroit DBs
log in as a user that has access to the user grid in partners
fun part: sift through the user grid and verify that each of the users in that list are unique and covers the 148 users …
=> fix: fixes pagination issue on detroit user grid

sites/partners/src/listings/PaperListingForm/index.tsx
- Closes #1055 
Clicking on the `Verify your listing data` link in the alert box at the top of the listing form for an unverified listing while on the second tab of the application should change you to the first page and then scroll to the bottom as it does now for the first tab.
Click on the verify link from the second page of the form, ensure it scrolls to the verify field
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …
=> fix: verify link should work on second application tab

backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10153.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts, backend/core/src/shared/units-transformations.ts, backend/core/src/units-summary/dto/unit-group.dto.ts, backend/core/src/units-summary/entities/unit-group.entity.ts, backend/core/src/units/types/unit-summaries.ts, backend/core/types/src/backend-swagger.ts, sites/partners/lib/helpers.ts, sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx, sites/partners/src/listings/PaperListingForm/formTypes.ts, sites/public/pages/index.tsx
- Addresses #1059 in part
This adds unit summaries to the listings list for use on the frontend browse and filtered pages.
Reseed the db locally and see that unitSummaries are on the listings.
=> feat: adds unit summaries to listings list to backend

backend/core/src/migration/1649709708991-detroit-email-updates.ts
Fix up the broken dev migration to check for the footer and register objects before inserting into them. The current error is `Cannot set property 'welcomeMessage' of undefined` because the register object on Detroit translations does not exist. (The diff is funky, I'd recommending reviewing with the `hide whitespace` setting).
=> fix: fix migration to check for new object

backend/core/src/auth/services/user.service.ts, backend/core/src/migration/1639051722043-add-mfa-related-columns-to-user-entity.ts, backend/core/src/seeder/seed.ts
This sets mfaEnabled to false, which should effectively disable mfa for Detroit.
Locally, reseed and no partners should have mfa enabled. Create a new partner and they shouldn't
=> feat: disable mfa for Detroit

sites/public/src/ListingView.tsx
- Closes #1074
Addresses this piece of QA: https://github.com/CityOfDetroit/bloom/issues/1074#issuecomment-1105548432
The image card tags on the listing detail page should reflect the tags on the directory page. What was missing was the color and icon of the coming soon label.
If you have one commit and message, …
=> fix: coming soon tag color on listing detail page

sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx, sites/partners/src/listings/PaperListingForm/index.tsx
- Closes #1161
Users were not able to save unit groups on a listing as `Open Waitlist`
We had two issues, the first being that we were incorrectly setting the form default (sometimes we have the already-saved `openWaitlist` and sometimes we have the draft data `openWaitlistQuestion`), and we were also incorrectly pre-populating that value.
You should be able to: Save a listing with units groups that have closed and open waitlists, and then open the listing form with closed/open waitlists, don't open any of the forms, just save, and have the waitlist values stay the same.
- Also review the acceptance criteria …
=> fix: cannot update waitlist status to open

sites/public/pages/index.tsx, ui-components/src/actions/LinkButton.tsx
- Closes #1147
Adds the new sign-up for notifications link. In core this is pulled off the jurisdictional `notificationsSignUpURL` field, but I'm not clear if we need that here since it's just Detroit? Open to feedback.
Ensure the homepage `Sign Up Today` button goes to the URL in the issue.
If you have one commit and …
=> feat: add new sign up link to home page

ui-components/__tests__/page_components/GetApplication.test.tsx, ui-components/__tests__/page_components/SubmitApplication.test.tsx, ui-components/src/helpers/address.tsx
- Closes #1190
QA from the initial issue: Leasing agent / pick up / drop off addresses should display the `street2` field.
Create a listing with a leasing agent address, ensure `street2` appears in the sidebar for the address.
If you have one commit and message, squash. If you need each message to be applied, rebase …
=> fix: show street2 for addresses

backend/core/src/migration/1651191466791-add-what-to-expect-additional-text-for-coming-soon.ts
See Slack thread: https://exygy.slack.com/archives/C0203460K6Y/p1651186335484579?thread_ts=1651186139.167809&cid=C0203460K6Y
Listings where the marketing type is coming soon should have their own default what to expect text set.
Reseed on dev, change to this branch, and run the migration. The one coming soon listing should have a `what_to_expect` text of the default, and an empty `what_to_expect_additional_text`. …
=> feat: set default what to expect text for coming soon listings

sites/public/layouts/application.tsx, sites/public/pages/listings.tsx, sites/public/pages/listings/filtered.tsx
- Closes #1215 
Remove the `Find rentals for me` button from the listing directory page.
Ensure the listing directory page and the filtered directory page does not have the button.
=> fix: remove link to eligibility calculator

backend/core/src/listings/listings.module.ts, backend/core/src/listings/listings.service.ts
When testing the google translation issues, I was getting `this.translationService.translateListing is not a function`, which is also showing up in dev's paper trail logs, and I found that removing the queue imports and injection resolved that issue. We should remove those anyway, since we're not currently using them.
=> Removes listing queue imports

backend/core/src/listings/dto/listing-filter-params.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/src/shared/query-filter/custom_filters.ts, backend/core/src/shared/query-filter/index.ts, sites/public/pages/listings/filtered.tsx, ui-components/src/helpers/filters.ts
- Closes https://github.com/CityOfDetroit/bloom/issues/1218
- Closes https://github.com/CityOfDetroit/bloom/issues/1219
- Closes https://github.com/CityOfDetroit/bloom/issues/1201
This fixes 3 issues:
1. The accessibility features filter should now internally be an or filter (e.g. they need elevator or parking on site)
2. The bedroom size filters should now function correctly (e.g. sro should only show listings where a unit group has an sro unit type select)
3. when connected to dev and selected `vacant units` for example the filter should now work correctly
**dev explanation**
for the third point above: 
the issue was that the filter was acting on the "outer" `unitGroups` instead of the inner query's `unitgroups` this was causing the issue and fixing the casing fixed the issue
Head to …
=> Detroit public filter fixes

sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
Quick update to check for the existing marking date, otherwise on a fresh listing edit form, if you open the coming soon sub-fields, the page breaks.
=> fix: check for existing marketing season

sites/partners/netlify.toml, sites/public/netlify.toml
No related issue, ad-hoc
For a few weeks Netlify has had an increasing frequency of oom errors during site builds. Rerunning the deploy sometimes works. After googling, this change seems to work for a lot of people experiencing the same issue.
=> fix: netlify oom build issues

sites/partners/netlify.toml
This adds a redirect for partners prod so that users who go to https://detroit-partners-prod.netlify.app, will be redirected to https://partners.homeconnect.detroitmi.gov.
The documentation for this can be found at https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file. Documentation on the use of `:splat` can be found at https://docs.netlify.com/routing/redirects/redirect-options/#splats
=> feat: adds partners redirect

ui-components/src/page_components/listing/AdditionalFees.tsx
Quick fix for bug where Additional Fees header always show since it was doing a null check on an empty array and this PR implements a length check instead.
=> fix: additional fees header showing bug (clean)

sites/public/pages/index.module.scss, sites/public/styles/footers.scss
This PR addresses #2927
This PR updates the spacing on the coming soon section, the regions section, and the footer.
This can be tested by using the Public preview and verifying that the changes reflect those seen in the issue.
If you have one commit and message, squash. If you …
=> fix: updated homepage spacing

sites/public/lib/helpers.tsx
This PR addresses #1431
On production currently, AMI %s and levels are not displaying on listings. The issue was in how we are passing cell data to tables.
Checkout a listing on dev that has AMI levels ([example](https://detroit-public-dev.netlify.app/listing/56256afd-1c63-462d-9b4b-0a1ffcf19e5c/clay_apartments_3300_mack_ave_detroit_mi))
And the same listing on this deploy preview ([example](https://deploy-preview-1432--detroit-public-dev.netlify.app/listing/56256afd-1c63-462d-9b4b-0a1ffcf19e5c/clay_apartments_3300_mack_ave_detroit_mi))
- Also review the acceptance …
=> fix: missing data in hmi tables

ui-components/src/blocks/ImageCard.scss
Quick fix for image centering within the new multi-photo gallery modal.
=> fix: centering modal images

sites/public/layouts/eligibility.tsx, sites/public/page_content/locale_overrides/general.json, sites/public/pages/finder.tsx, sites/public/pages/index.tsx, sites/public/styles/forms.scss, sites/public/styles/headers.scss, sites/public/styles/overrides.scss, ui-components/index.ts, ui-components/src/forms/Field.stories.tsx, ui-components/src/forms/Field.tsx, ui-components/src/global/forms.scss, ui-components/src/headers/StepHeader.docs.mdx, ui-components/src/headers/StepHeader.scss, ui-components/src/headers/StepHeader.stories.tsx, ui-components/src/headers/StepHeader.tsx, ui-components/src/locales/general.json, ui-components/src/navigation/ProgressNav.docs.mdx, ui-components/src/navigation/ProgressNav.scss, ui-components/src/navigation/ProgressNav.stories.tsx, ui-components/src/navigation/ProgressNav.tsx
This PR primarily addresses #1422 and #1433. Technically, #1423 as well which is handled by creating the feature branch.
This PR implements the path to the "/finder" page with a new button on the homepage, handles the design of the listing finder with the bordered field, progressNav and stepHeader which were brought over from Core, and the functionality of filtering the listings based on user's form choices for Q1. It also establishes a pattern how the form data will be stored across sections of the form and how to limit redundant code. This is subject to potentially change as more questions are implemented but it serves as an initial approach to how the user inputs could be handled.
Two thing to verify on Design @slowbot:
1) Button sizes seemed a bit bigger in the Figma than the ones I …
=> 1422/finder scaffolding + Q1

backend/core/src/activity-log/entities/activity-log.entity.ts, backend/core/src/auth/entities/user-preferences.entity.ts, backend/core/src/migration/1665776578492-remove-activity-log-user-relationship-on-delete.ts, sites/partners/pages/index.tsx, sites/partners/pages/users/index.tsx, ui-components/src/tables/AgTable.tsx
This PR addresses #3137
There is a bug in how user deletion is currently setup. Due to table relationships between the user_accounts and activity_logs along with user_preferences, users are unable to be deleted if they have any preferences or have done any activities. This fixes it by adding null to the user column in activity_logs when a user is deleted and cascading deletion of user_preferences.
**NOTE:** This is slightly different from the core/HBA fix as they do not have the user_preferences table so that functionality is new.
In order to test this you'll need to have two accounts. One account you'll need to do an action with (e.g. close a listing) and the other account will be the one to delete the first account.
To test the the user_preference change you'll need to delete a user …
=> fix: allow the deletion of users

sites/public/page_content/resources/sidebar.md, sites/public/pages/additional-resources.tsx, sites/public/pages/get-assistance.tsx, sites/public/pages/housing-basics.tsx, sites/public/src/ResourceLinkCard.tsx
This PR addresses #3269
This PR corrects the heading order on the get-assistance page. Since it also touches the sidebar content (Contact info), it adjusts heading levels for housing-basics and additional-resources but in ways that correct the order there as well.
This can be tested by using inspect element on the page and ensuring that the content of the footer doesn't contain heading tags. 
OR
Repeat the steps below on the get-assistance page along with housing basics and additional resources.
1. Click your voiceover modifier key (in my screenshot it is caps lock) + U
2. Use the left or right arrow key until you locate the Headings Menu
3. Use the down arrow to the headings on the page and their respective levels
4. Ensure it matches the discussed changes above
- …
=> fix: correct get-assistance headings

sites/public/pages/finder.tsx
This PR addresses #1536 
This change improves the screen reader experience when navigating between pages of the Rental Finder form. Previously, we were approaching this issue with the hard rule that no non-actionable item should ever have the tabIndex attribute. After more research and discussions with LH, it seems that approaching this rule with more nuance could improve the SR experience. Also to note, our current implementation allows for the container to receive focus but that hasn't been performing consistently nor helping the SR experience. It was made more as a temporary fix and I imagine this to be more precedent setting on our use of tabIndex.
Resources to support:
1) Representatives of LH shared that tabIndex attributes on non-actionable items is a pattern that they are familiar …
=> fix: tabIndex approach

sites/public/styles/blocks.scss, sites/public/styles/footers.scss, sites/public/styles/forms.scss, sites/public/styles/headers.scss, sites/public/styles/listings.scss, sites/public/styles/overlays.scss, sites/public/styles/overrides.scss, sites/public/tailwind.config.js
I'd recommend reviewing with `hide whitespace`, very few lines changed.
We're seeing this grid issue locally but not in Netlify environments. The issue was that one class `md:grid-cols-3` was in the DOM but wasn't actually being applied.
The class is created dynamically like so: `if (props.span) gridCellClasses.push('md:col-span-${props.span}')`
I first found this [StackOverflow post](https://stackoverflow.com/questions/71937890/tailwind-css-classes-show-up-in-the-dom-but-the-styles-are-not-being-applied) which did solve the issue. It indicates that Tailwind scans for used class names, and since we don't explicitly have `md:grid-cols-3` as a string, but with the var in the string literal, it wouldn't be added.
I think the core of that issue is that UIC has `purge: false` in its tailwind …
=> fix: release issue with filter grid

detroit-ui-components/src/headers/PageHeader.scss, sites/public/tailwind.config.js
This PR addresses #1570
Fixes the three UX issues in the ticket.
Check out the issues and compare to the deploy previews. Two of the issues are not present locally, so need to test in Netlify.
If you have one commit and message, squash. If you need each message to be applied, …
=> fix: release ux issues

backend/core/src/auth/services/user.service.spec.ts, backend/core/src/auth/services/user.service.ts, backend/core/types/src/backend-swagger.ts, detroit-ui-components/src/locales/ar.json, detroit-ui-components/src/locales/bn.json, detroit-ui-components/src/locales/es.json, detroit-ui-components/src/locales/general.json, detroit-ui-components/src/locales/vi.json, detroit-ui-components/src/locales/zh.json, sites/partners/src/pages/forgot-password.tsx, sites/public/src/pages/forgot-password.tsx
This PR addresses #1546 
This PR is a cherry-pick from Core (with a few adjustments) so that entering an email on the forgot password page will return a neutral message that doesn't indicate if the email exists or not. This PR also adds tests to verify the backend changes required.
This can be tested by submitting an email that exists in the db on the forgot password page and then one that doesn't to ensure that the UX is the same. This should be tested on both the partner's and public side. 
- Also review the acceptance criteria on the Netlify deploy preview (noting …
=> fix: cherry-picked forgot-password from core

sites/public/src/pages/finder.tsx
This PR addresses #1562 
This PR tailors the focus behavior on the rental finder form to better communicate changes in the form section. Now when clicking next or previous results in a change in form section, the focus should land on the step header rather than the question text. If navigating between questions within the same section, the focus still lands on the question text.
This can be tested by going through the rental finder form with screen reader enabled and noticing where the focus lands after clicking next or previous. This behavior should also be verified on NVDA.
- Pull the changes down locally and test that the acceptance …
=> fix: custom focus management

detroit-ui-components/src/text/Description.scss, detroit-ui-components/src/text/Description.tsx, sites/public/styles/listings.scss
[Slack thread
](https://exygy.slack.com/archives/C02G1S19QA2/p1678736662433509)
Sort of an unusual way to tackle this one, but the work to align the Description component is already in [PR in UIC](https://github.com/bloom-housing/ui-components/pull/84). This copy/pastas that locally, and adds a few expected Detroit overrides.
Once the Description PR goes into UIC we could remove this locally.
=> fix: description grid misalignment

backend/core/src/listings/helpers.ts, sites/partners/__tests__/pages/users/index.test.tsx
This PR addresses #1525 
Manually deploying the backend after merging in listings export resulted in the following error. 
I believe it is caused by attempting to import backend/core which was not included in its package.json file. Additionally, pretty sure that importing a package that the file itself belongs to would create a circular dependency.  The fix above should address that.
Also, realize the unit tests need to be updated to reflect the change to Export to CSV language so that is handled here as well.
Not sure here.
- Also review the acceptance criteria on …
=> fix: listings export clean up

sites/partners/cypress/integration/listing.spec.ts, sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
[Slack thread](https://exygy.slack.com/archives/C02G1S19QA2/p1678728712555439) #1588 
At the moment there is a `Is there an application due date?` question, but you can't save a value in it, and you also can't save an application due date. Decision was made in feature sync to remove the field.
=> fix: remove the due date question

detroit-ui-components/src/forms/Field.tsx, sites/public/src/components/filters/FilterForm.tsx, sites/public/src/components/finder/FinderRentalCosts.tsx, sites/public/src/pages/finder.tsx
This PR addresses #1563 
Changed input type from number to text, but restricted signs to numbers. This way we don't have scrolling, and screen reader announces it as `text field` which seem more reasonable than `stepper`.
Go to `/listings` -> open filters, using screen reader focus on min / max rent fields -> they should act as text field, but accept only numbers. Also scrolling inside field shouldn't change value.
Do the same for min/max rent fields in `/finder`
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include …
=> fix: change min/max rent inputs from number to text with only numbers

backend/core/src/listings/helpers.ts, backend/core/src/listings/listings-csv-exporter.service.ts
This PR addresses #1597
This PR addresses the 4 issues found in bash earlier (excluding the verifiedAt date issue since its out of scope).
Issue 1: Column should be Developer/Property Owner rather than Developer Property Owner  
Issue 2: On the unit groups csv, ami charts have duplicates.  
Issue 3: On the listings csv, the leasing management company is not successfully pulling in the data  
Issue 4: On the listings csv, you can upload multiple paper applications in different languages but only one is showing in the paper app url field  
Only thing to note here is on the third issue. Originally, it was set up to pull in listing.managementCompany which is a field that we seed with but no longer can be set from the partners side. Instead, the Property Management Company field label is set …
=> fix: resolve bugs from bash

.gitignore, backend/core/src/auth/controllers/user.controller.ts, detroit-ui-components/src/locales/general.json, sites/partners/__tests__/pages/users/index.test.tsx, sites/partners/src/lib/hooks.ts, sites/partners/src/page_content/locale_overrides/general.json, sites/partners/src/pages/index.tsx, sites/partners/src/pages/users/index.tsx
This PR addresses #1594 
This addresses the three issues related to user export found in the bug bash yesterday
1. Spinner doesn't appear when you click the "Export to CSV" button
2. Only 10 users were getting returned
3. Success toaster kept reappearing, especially if you click "Users" navigation link after the toaster had been dismissed
In dev the first two are fairly hard to test since the export is fast enough that the spinner doesn't really appear and there are 10 or less users in the dev environment. You can add more users to get above the 10 threshold.
Steps to test # 3
- Go to users page and click on "export to CSV"
- wait for the success message to appear and disappear
- Click on the "USERS" navigation tab. 
- The toaster should not reappear …
=> fix: user export fixes

backend/core/package.json, yarn.lock
This PR addresses #3317 
Locally the backend runs and can be built. However, due to the way Heroku instances are deployed there is a dependency mismatch on the bull dependency (this is something only used by Detroit and not core). This PR upgrades @nestjs/bull to resolve that error. Error for reference: https://dashboard.heroku.com/apps/bloom-detroit/activity/builds/a1520773-4078-4ca2-8c3a-d63faeef8ba9
Reason for the error:
- locally when installing the yarn packages it uses the yarn.lock file at the root of the directory. This tells yarn exactly which version of everything to download and install. 
- When deploying to Heroku it does not know about the yarn.lock file since it only knows about the backend/core directory (which has an empty yarn.lock file). So instead it has to install the …
=> fix: update bull version

backend/core/src/shared/query-filter/index.ts
This PR addresses #1633
It changes comparator signs so it matches field
Go to listings, set min/max rent filters. Now it should properly show filtered listings.
Also check for finder
If you have one commit and message, squash. If you need each message to be applied, rebase and …
=> fix: flip min rent with max rent

sites/public/src/lib/helpers.tsx, sites/public/src/pages/finder.tsx, sites/public/src/pages/listings.tsx, sites/public/src/pages/listings/filtered.tsx
This PR addresses #1632 
We were sending formatted currency string, so with commas. This PR removes them before form submitting.
min and max filter fields are switched (so min act as max, and max as min) -> it's solved in different PR
Go to listings page, and filter by min / max rent, type number bigger that 1000. Check if it filters correctly. Same for finder.
You can verify if it passes "number string" without commas to query url params, and if it sends it in this format to backend.
- Also review the acceptance criteria on the Netlify deploy preview (noting that …
=> fix: format currency before filter form submit

sites/public/styles/overrides.scss
https://github.com/CityOfDetroit/bloom/pull/1642
Just updates origin to dev, you can check out the other PR for details
=> fix: cant filter on mobile

sites/public/styles/overrides.scss
This PR addresses #1641
Allows users to see the buttons in the footer of the filter modal on the public site.
You have to test on a mobile device - the issue doesn't appear in the mobile emulator. You can visit the [deploy preview link](https://deploy-preview-1642--detroit-public-staging.netlify.app/).
This issue in part stems from the fact that the URL across different mobile browsers is in a different place and is a different height, so `100vh` is treated differently. The URL box in latest Safari is on the bottom vs in Chrome it's on the top. 
There are new dynamic viewport values that take this difference into account on mobile (documentation [here](https://web.dev/articles/viewport-units)). This looks to work great on recent browsers, but because it's new it's not supported across all …
=> fix: cant see buttons in drawer footer

shared-helpers/src/AuthContext.ts, sites/partners/cypress/e2e/listing.spec.ts, sites/partners/src/pages/reset-password.tsx, sites/public/src/pages/reset-password.tsx
This PR addresses #1640 (BUT JUST NOW WITH DEV)
This error is coming from attempting to sign the user in after they've successfully reset their password. Resolving this issue is still in progress but this PR will force users to sign-in again and gain access to the partners portal. Given the severity of the issue and scale of users locked out, I think this change is appropriate to buy more time for a comprehensive fix.
Note: I included messaging to the sign-in page about successfully updating password but that alert box will not show success site alert messages (without a change to UIC) so I chose a notice style as opposed to having no communication.
This can be tested by creating an account with an email you have access to, following the forgot password flow until you are successfully …
=> fix: force users to resign-in pt. 2

shared-helpers/src/AuthContext.ts, sites/partners/cypress/e2e/listing.spec.ts, sites/partners/src/pages/reset-password.tsx, sites/public/src/pages/reset-password.tsx
This PR addresses #1640 
This error is coming from attempting to sign the user in after they've successfully reset their password. Resolving this issue is still in progress but this PR will force users to sign-in again and gain access to the partners portal. Given the severity of the issue and scale of users locked out, I think this change is appropriate to buy more time for a comprehensive fix.
Note: I included messaging to the sign-in page about successfully updating password but that alert box will not show success site alert messages (without a change to UIC) so I chose a notice style as opposed to having no communication.
This can be tested by creating an account with an email you have access to, following the forgot password flow until you are successfully logged in.
Steps to review …
=> fix: force users to resign-in

backend/core/src/auth/services/user.service.ts, shared-helpers/src/AuthContext.ts, sites/partners/src/components/users/FormUserConfirm.tsx, sites/partners/src/pages/reset-password.tsx, sites/public/src/pages/reset-password.tsx
This PR addresses #1640 
This is a more long-term fix to the password reset and account confirmation issues. By passing the token explicitly, the userControllerProfile() stops throwing an error. This PR also fixes an issue where the isUserConfirmationTokenValid was being called multiple times and falsely triggers the link expired modal.
This can be tested by going through the password reset and new user confirmation on both the public and partner's site.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any …
=> fix: explicitly pass token

backend/core/src/applications/applications.controller.ts, backend/core/src/auth/controllers/user.controller.ts, backend/core/src/listings/listings.controller.ts
This PR addresses #1659 
Currently when a string that isn't a UUID is passed into endpoints that take a UUID as a path parameter it gets all the way to the DB layer before an error is thrown. This is dangerous in that a malicious actor could pass in some nefarious string and get close to messing with the database or getting information from the database. We don't believe this could actually happen, but for an extra level of security this PR adds UUID validation at the controller level to stop these calls well before the DB
- Start up the backend and go to swagger `http://localhost:3100/docs`. 
- Test /listings/{id} endpoint by passing in a string that isn't a UUID
- The returned error should be a 400 instead of a 500
- Do the same for /applications/{id} and /user/{id}
- Also you can test …
=> fix: add uuid validation at controller level
