CityOfDetroit/bloom

backend/core/scripts/import-listings-from-arcgis.py, backend/core/scripts/main.py
Write a script to pull listing data from ArcGIS
Done criteria: a Python script that reads in all listing data from ArcGIS and logs the name of each listing to the console
Note: this is a sub-task within #45
=> Pfeeny5 import arc gis data

README.md, package.json
Some quality of life commands:
install:backend - cd's to backend/core and runs install and db:reseed
install:all - runs install in the outer dir as well as backend/core
clean - removes common .gitignore files so you can run a clean install
=> Add a few commands to package.json.

backend/core/package.json, backend/core/scripts/import-listing-from-json-file.ts, backend/core/scripts/import-listings-from-arcgis.py, backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/listings-importer.ts, backend/core/scripts/minimal-listing.json, backend/core/src/auth/authz_policy.csv, docs/Authentication.md
Addresses https://github.com/CityOfDetroit/affordable-housing-app/issues/75
This PR makes a number of changes in order to allow for importing listing data from Detroit's ArcGIS DB to the Bloom DB:
- Opens up permissions such that *any logged-in user* has permission to create a new `property` and `listing`
- Note: this is definitely **not** behavior we want when we launch the site; we are doing this in the interest of moving quickly.
- Converts `listings-importer.ts` into a "library" with a single `importListing` function, and pulls out `import-listing-from-json-file.ts` to handle importing a single new listing from a JSON file (this was the existing behavior of the `listings-importer.ts` script)
- This change also adds a `minimal-listing.json` as an example of the simplest valid listing …
=> Modify scripts to allow for importing listings from ArcGIS

backend/core/README.md, backend/core/package.json
No Issue
Adds a package.json command for starting the backend server in debug mode
- [x ] This change requires a documentation update
=> Adds start command for backend in debug mode

backend/core/README.md, backend/core/package.json
None
Removes the broken debug command added in PR #15 and updates readme.
=> Removes broken debug command, updates readme

backend/core/.env.template, backend/core/README.md, backend/core/package.json
No attached issue
Adds two things to help with setting up the test db for end-to-end tests
- Adds uuid extension step to test db initialization
- Adds `TEST_DATABASE_URL` to `env.template` so it's clear how to set the test database url
=> Adds uuid extension step to e2e tests, and update to .env.template

backend/core/scripts/import-listing-from-json-file.ts, backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/listings-importer.ts, backend/core/test/authz/authz.e2e-spec.ts
This clean-up change does three unrelated things:
- Fixes lint errors in `/backend/core/scripts` (now `yarn lint` reports only warnings, no errors)
- Removes a workaround from `import-listings-from-detroit-arcgis.ts` that prevented listings from being created with a `closed` status since (previously) the DB didn't know about that enum value.
- Removes a test that indicated that a logged-in user does not have permission to `POST /listings`. We (temporarily) opened up permissions to allow this (https://github.com/CityOfDetroit/affordable-housing-app/issues/85).
- Note: I wanted to reverse the test (instead of just deleting it) to show the current state of the world (i.e. that any logged-in user *can* create a new listing). But that would require first sending `POST` requests for the …
=> Remove a failing test, and clean up listing-import scripts

sites/partners/pages/index.tsx, sites/partners/src/listings/PaperListingForm/index.tsx
Enables the view (NOT the functionality, I haven't been able to get the database to update yet) for adding / editing listings in the partner portal. Since we aren't focusing on applications, I replaced the link to the application view with a link to a form to edit the listing content, auto-populated with the existing listing data.
Launch the partner portal and test the Add Listing button and the listing link.
=> Enable view for add / edit listings from partner's portal

.github/card-labeler.yml, .github/workflows/auto-assign-project.yml
If an issue is moved into the Epic Tracking column of the backlog, add the tracking label to it.
=> Add automatic labels for epic and milestone tracking.

sites/partners/src/listings/PaperListingForm/index.tsx
Fix lint errors I caused in #99
=> Fix lint errors

sites/partners/pages/index.tsx, sites/partners/pages/listings/add.tsx
For now, only admins should be allowed to add new listings.
Hides the "Add Listing" button for non-admins. Also shows an error if a non-admin tries to navigate to the /listings/add page.
Run the partner portal locally. Log in as an admin and view the "Add Listings" page. Log in as a non-admin and see the button to add a listing is gone. If you try to go to localhost:3001/listings/add, this should also fail with an error message.
=> Allow only admins to add new listings

.travis.yml
Addresses #86 
Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Check whether Travis CI runs on this PR and the status of the run.
=> Add a Travis config file to build sites.

docker-compose.yml
Addresses #58 
This variable is used to override BACKEND_API_BASE for any logic that is
sent to the client; i.e. anything in ui-components/. This allows us to
specify different URLs for the logic running in the client and the logic
running inside the container.
Run `docker-compose up` and attempt to login via the public site.
=> Use the INCOMING_HOOK_BODY env variable.

bin/.env.template, bin/run_prod_database_migration.sh
Addresses #163 
When running this script, it will download the cloud_sql_proxy, connect
to the database, and run any pending migrations.
Copy `bin/.env.template` to `bin/.env` and update with the production username/password. Then run the script.
=> Create a script for running the database migration in prod.

CHANGELOG.md, sites/partners/README.md, sites/partners/package.json, sites/public/README.md, sites/public/package.json
Addresses #194
- Add debug flags to the `yarn dev` commands for the frontends.
- Also updates the readmes with instructions for adding a vscode launch.json config
- Moves the partners debug port from `2930` to `2931` to so debug and http ports are aligned.
- Adds debug flag to public site with debug port at `2930`
=> Add debug flags and instructions for debugging frontends

backend/core/scripts/import-listings-from-detroit-arcgis.ts, backend/core/scripts/listings-importer.ts, backend/core/scripts/minimal-listing.json, backend/core/src/listings/dto/listing.dto.ts
Addresses #196 
Recent changes broke the listing-importer scripts. This change makes a number of small fixes so that these scripts work again:
- Set a `unit.status` that conforms to the new `UnitStatus` enum
- Explicitly set `listing.displayWaitlistSize`
- Associate `units` and `buildingAddress` with the `listing` (previously, these were tied only to the `property`; now the `ListingCreateDto` expects to include `units` and `buildingAddress` - I believe this is part of the migration of fields from `property` to `listing`)
- Within `ListingCreateDto`, double the max number of units (from 256-->512), since there is at least one listing in Detroit with more than 256 units.
```
$ yarn ts-node scripts/import-listing-from-json-file.ts http://localhost:3100 test@example.com:abcdef …
```
=> Fix data import scripts

sites/public/pages/eligibility/age.tsx, sites/public/pages/eligibility/bedrooms.tsx, sites/public/pages/eligibility/disability.tsx, sites/public/pages/eligibility/income.tsx, sites/public/pages/eligibility/section8.tsx, sites/public/pages/eligibility/welcome.tsx
Used ESLint to fix the formatting in the eligibility questionnaire files.
I'm separating this change from #208, so it's more clear which changes are related to adding the progress bar.
=> [Eligibility Questionnaire] Formatting fix

backend/core/src/listings/dto/listing.dto.ts, backend/core/src/listings/listings.controller.ts, backend/core/src/listings/listings.service.spec.ts, backend/core/src/listings/listings.service.ts, backend/core/src/shared/dto/filter.dto.ts, backend/core/src/shared/filter/index.ts, backend/core/types/src/backend-swagger.ts, sites/public/lib/hooks.ts, sites/public/pages/listings.tsx, ui-components/src/locales/general.json
#253 
Frontend uses exported backend filter definitions instead of defining its own.
=> Consolidate filter definitions

sites/partners/pages/index.tsx, sites/partners/src/listings/Aside.tsx
This reverts commit e2c348a59f40dd6832b4675e12fd4d4106d48fab.
Addresses #280 
Reverted back to original Partner Portal implementation without admin edit controls.
=> Revert "Edit button removal for non-admin users (#184)"

.travis.yml
Addresses #282
Add the existing ui-components a11y testing target to Travis.
View Travis checks and confirm the a11y testing is passing.
=> Add ui-components a11y testing to Travis config.

Dockerfile.sites-partners, Dockerfile.sites-public
Addresses #277 
It is not enough to add to the yaml file as environment variables because those are passed in at run time. They need to be passed in at build time through these Docker files.
=> [Translations] Add the Detroit languages to the Docker file

backend/core/scripts/import-listing-from-json-file.ts, backend/core/scripts/import-listings-from-detroit-arcgis.ts
Suggests using the admin user in the importer script, which is necessary to have the right permissions to update the DB.
=> Update example importer script

sites/public/src/ListingView.tsx, ui-components/src/page_components/listing/AdditionalFees.tsx, ui-components/src/page_components/listing/UnitTables.tsx
Addresses #330 
- Don't display Built, Neighborhood, or Additional Fees sections if we don't have data for them.
- Doesn't display the "square feet" text if there isn't data on square footage.
Before:
After:
I checked listings with both populated and unpopulated data and verified the formatting looked as expected.
=> Improve features section

ui-components/src/page_components/listing/ListingsList.tsx
- Closes #346  
Before:
After:
=> move details button

sites/partners/layouts/index.tsx, sites/partners/styles/overrides.scss, sites/public/styles/overrides.scss, ui-components/src/headers/SiteHeader.tsx
Addresses #543
Remove the widths set on the elements in the header logo lockup
Before
Public
Partners
=> Fix header breaking site width

backend/core/scripts/import-listings-from-csv.ts
- Closes #445 
Listing CSV importer grabs AMI data from "Pct AMI" columns instead of "Affordability Mix" column.
Run the import script on the full HRD data spreadsheet (not the filtered sheet of only regulated data). Note that this requires deleting the first two rows of data.
=> Import listing data from AMI columns instead of affordability mix

.travis.yml, Dockerfile.sites-partners, Dockerfile.sites-public, Dockerfile.ui-components, backend/core/Dockerfile
- Addresses #293
Upgrades the Node version in the Dockerfiles to 14 so we can deploy.
Build the sites from Dockerfiles.
=> Upgrade Dockerfiles to Node 14.

backend/core/scripts/import-listings-from-csv.ts
- Closes #453
The HRD spreadsheet includes listings that are both actively in use (i.e. people could/do live there presently) and those that are scheduled to be used in the future (e.g. buildings that are being built or are not yet set up to house people). This change filters out the latter, in our CSV import script.
The criteria for the filtering (if the listing is not "existing occupied" and its stage in the development pipeline is less than "3") come directly from a meeting with HRD. With this filtering in place, there are a total of 348 listings remaining.
- Download the "Master Data Sheet" spreadsheet (note: this isn't available anywhere right now; [I'm asking Safiya](https://github.com/CityOfDetroit/bloom/issues/453#issuecomment-923196517) if this can be uploaded to our shared Box) …
=> Filter out (in the listing importer script) listings that are not far enough along in the development pipeline

CHANGELOG.md, backend/core/src/seeds/listings/listing-detroit-10147.ts, backend/core/src/seeds/listings/listing-detroit-10157.ts, backend/core/src/seeds/listings/listing-detroit-10158.ts
- Closes #588
Remove the application methods from the seed listings. This was causing an apply button that didn't function.
Reseed the database and then view the New Center Commons listing.
=> Remove extraneous application methods from seed listings.

CHANGELOG.md, sites/public/pages/listings.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> [Filtering] Add senior housing filtering to the filter modal

backend/core/scripts/import-helpers.ts, backend/core/scripts/import-listings-from-csv.ts
- Closes #491 
- Closes #465 
- Closes #446
This change causes the CSV listing import script to check the "HUD Client group" column to determine if the listing is reserved for specific populations. The behavior (based on a meeting with HRD) is:
- If the HUD client group is "wholly physically (disabled|handicapped)", the listing is considered reserved only for "specialNeeds"
- If the HUD client group is "wholly elderly housekeeping", the listing is considered reserved only for "senior62"
- Any other HUD client group is ignored. The other HUD client groups that I saw in the spreadsheet:
- "Elderly"
- "Indv. families - not eld/ handicap"
- "Family & Elderly"
- "Partially elderly congregate"
- "Chronically Mentally Ill"
- Reseed the database
- Confirm the number of listings with …
=> Import reserved community types

ui-components/src/helpers/filters.ts
Addresses #NA
Add a comment explaining why the types for the ListingFilterState have `string | ...`
=> Add comment explaining types for ListingFilterState interface

sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/navigation/ProgressNav.tsx
Addresses #267
Add a sr only text that says "current step" as you're navigating through the progress menu.
Tab through the progress bar with a screen reader.
=> Add current step prompt for screenreader

sites/public/lib/HorizontalScrollSection.tsx
Fix `Cannot read property 'removeEventListener' of null` errors due to the HorizontalScroll component.
Puts the event listener on the container using the onScroll prop which react handles automatically instead of useEffect which doesn't guarantee the existence of the ref.
Load the homepage, click on a latest listing to navigate.
=> Fix HorizontalScroll removeEvent

sites/public/src/forms/filters/FilterForm.tsx
- Closes #681
Remove 'Independent living community' filter from 'Filter Results' page. 
=> Remove independent housing filter.

sites/public/pages/index.module.scss, sites/public/pages/index.tsx
- Addresses #674 
Hardcode some temporary images for the neighborhood section for our demos this week.
Note that we still need to get our own images to use here, so this is just temporary to show what the website will look like.
=> Hardcode temporary neighborhood images

sites/public/pages/index.tsx
=> Update homepage to handle no latest listings gracefully

sites/public/page_content/locale_overrides/ar.json, sites/public/page_content/locale_overrides/bn.json, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json
- Closes #694
Small copy change for the reset button on listings filters.
Before:
After:
Go to listings, apply a filter.
=> Update reset button copy.

sites/public/pages/listings.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #692
Small update to the copy on the "qualifications" button on the listings page.
Before:
After:
Go to the listings page.
=> Update listings qualification button copy.

sites/public/styles/overrides.scss
- Addresses #714
Tweaks the header text css to center align it better.
Mobile should be unchanged
=> Tweak header css to center align better

ui-components/__tests__/icons/Icon.test.tsx
Add "ariaHidden" as an option prop on the Icon component to support having decorative icons that are hidden from the accessibility tree.
I intend to propose this change in the upstream repo as well
-See https://github.com/CityOfDetroit/bloom/pull/753 for an example usage
- Added test to make sure aria-hidden was set on the resulting span
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any …
=> Add support for ariaHidden to the Icon component

sites/public/layouts/application.tsx, sites/public/pages/feedback.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #497
Add a feedback page that embeds the google form. The link is added to the footer.
=> Add Feedback page

backend/core/scripts/minimal-listing.json, backend/core/test/listings/listings.e2e-spec.ts
- Closes #771
When https://github.com/bloom-housing/bloom/pull/1850 was pulled into, it introduced a lot of extra requirements around "publishing" a listing. This broke the minimal listing JSON file. This PR updates the minimal listing so that it can be "published", and adds a test to catch breaking changes.
To run the test:
`yarn test:e2e:local --testPathPattern listings.e2e-spec --testNamePattern "should create a new listing"`
To import the minimal listing:
`yarn ts-node scripts/import-listing-from-json-file.ts http://localhost:3100 admin@example.com:abcdef scripts/minimal-listing.json`
=> chore: test for create listing

backend/core/src/app.module.ts
Maybe this will fix the issue we see?
=> fix: increase redis timeout

sites/public/pages/account/edit.tsx
- Closes #766 
- Addresses #766
Adds options to update email and sms notification in user settings.
=> Add checkboxes to user settings.

sites/public/styles/overrides.scss, ui-components/src/headers/SiteHeader.tsx
The "Log Out" option in the dropdown menu in desktop mode didn't extend all the way to the end of the dropdown menu, and the icons on the menu item in mobile mode were getting pushed to the next line.
=> fix: navbar dropdown/menu items

backend/core/src/migration/1637700649083-alter-user-preferences.ts
=> Create missing migrations

backend/core/src/shared/email/email.service.ts, backend/core/src/views/new-listing.hbs, backend/core/src/views/update-listing.hbs
- Addresses #699, #696, #697
Creates function for filling out the templates for sending emails about new listings and updated listings. Opening a separate for email translations
=> Add new listing and update listing email templates and send email

backend/core/package.json, backend/core/scripts/import-realpages-availability-report.ts, backend/core/src/seeds/listings/listing-detroit-10202.ts, backend/core/src/seeds/listings/listing-detroit-treymore.ts, yarn.lock
- Closes #790
This commit adds an import script that reads availability xml generated from a Realpages report.
1) `cd backend/core && yarn db:reseed:detroit`
2) Find the db ID for River Towers:
`select id, name from listings where listings.name='River Towers';`
3) Get the `Availability.xml` report for River Towers, and then run
`yarn ts-node scripts/import-realpages-availability-report.ts --email=admin@example.com --password=abcdef --backendUrl=http://localhost:3100 --reportFilePath=Availability.xml --listingId=<listing id from step 2> --mapping "1.5 B:oneBdrm" --mapping "1B:oneBdrm" --mapping "1B PH:oneBdrm" --mapping "2B:twoBdrm" --mapping "2B Bal:twoBdrm" --mapping "2B PH:twoBdrm"`
=> feat: import Realpages availability report

backend/core/src/detroit-seed.ts, backend/core/src/seeder/seeder.module.ts, backend/core/src/seeds/listings/listing-detroit-10136.ts
- Addresses #790
`cd backend/core && yarn db:reseed:detroit`
=> chore: add Martin Luther King II to seed script

sites/public/pages/index.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Addresses #674
- Addresses #672 
Adds translations to the Latest listing section and the Neighborhoods section. I think some of the bedroom translations aren't perfect but it was the best I could figure out from google translate for now. Hopefully the real translators can do a better job.
Go to the homepage and toggle different languages.
=> Add translations to homepage

backend/core/scripts/import-listings-from-csv.ts
The current CSV import script unconditionally makes a new listing for each valid row in the csv file. This PR skips listings that are already present, based on the HRD id.
Run the import script twice, observe only one set of listings being created.
=> Skip importing existing HRD listings

sites/public/lib/HorizontalScrollSection.module.scss, sites/public/lib/HorizontalScrollSection.tsx, sites/public/pages/index.module.scss
- Closes #776
- Addresses #776, #672
Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change. I also took the liberty of adding the translation strings for the titles and subtitles.
Navigate to home page, select Arabic locale.
=> fix: rtl horizontal scroll view

backend/core/src/listings/entities/listing-features.entity.ts, backend/core/src/listings/entities/listing.entity.ts, backend/core/src/listings/listings.module.ts, backend/core/src/migration/1637710104539-add-listing-features.ts
- Closes #786 
Creates a new ListingFeatures table with a 1-1 relationship with the Listings table. This table has building features that are filterable.
=> Create ListingFeatures table for filterable listing features

sites/public/lib/FindRentalsForMeLink.module.scss, sites/public/lib/FindRentalsForMeLink.tsx, sites/public/pages/listings.tsx, sites/public/pages/listings/filtered.tsx, sites/public/styles/overrides.scss, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
Update the banner for the listings page and the filtered page.
[Mocks](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=3602%3A21696)
=> Update the banner for the listings page

backend/core/package.json, backend/core/scripts/import-amc-waitlist-report.ts, yarn.lock
- Closes #800
AMC waitlist reports come in XLSX format. This script imports the XLSX file, and looks for a cell containing the words "Total on Waitlist".
1) Obtain an AMC `waitlist.xlsx` file
2) Get the listing id of the corresponding listing:
```
psql bloom -c "select id, name from listings where name='<name of listing>';"
```
3) Run the script:
```
yarn ts-node scripts/import-amc-waitlist-report.ts --email=admin@example.com --password=abcdef --backendUrl=http://localhost:3100 --reportFilePath=waitlist.xlsx --listingId=<listing id from step (2)>
```
You should see the "Open Waitlist" header appear on listings, if the waitlist was opened through the script:
=> feat: import AMC waitlist reports

sites/public/lib/FindRentalsForMeLink.module.scss
I had made this tweak to the padding, but forgot to commit and upload it. Makes the button look better on mobile.
=> Tweak padding for Find rentals for me link

sites/public/cypress.json, sites/public/cypress/integration/navigation.ts, sites/public/layouts/application.tsx, sites/public/styles/overrides.scss, ui-components/src/headers/SiteHeader.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #816
Update the site header to the new design:
[Mocks](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=3540%3A13497)
=> Update header to new design

sites/public/pages/index.module.scss, sites/public/pages/index.tsx, sites/public/styles/overrides.scss
- Closes #818
Overrides the default ListingCard styling to match the mocks. I also change the Latest Listings cards on the homepage to reuse these new ListingCard components since the styles now match.
[Mocks](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=3540%3A13497):
=> Update Listing Card styling to match new mocks

sites/public/lib/helpers.tsx, sites/public/src/ListingView.tsx, sites/public/styles/overrides.scss, ui-components/src/blocks/ImageCard.tsx, ui-components/src/icons/Icon.tsx, ui-components/src/icons/Icons.tsx, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json, ui-components/src/text/Tag.tsx
- Closes #819
This commit also adds an accessibility icon, and adds that icon to accessible tags on listing cards.
Go to the home page, scroll the latest listings to the Oak Village Independence entry.
=> feat: add icon to tag component

sites/public/cypress/integration/eligibility-questionnaire.ts, sites/public/pages/index.tsx, sites/public/styles/overrides.scss, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #817 
- Addresses #817
UI change to separate two home page buttons and change their text and color.
pieces in ui-components
=> Separate two buttons and change color and text on homepage.

backend/core/src/views/new-listing.hbs, backend/core/src/views/update-listing.hbs
Changes the text color for the "See Listing" and "See Listing & Apply" button in email notifications. 
See images below
=> Change color of text in "See Listing & Apply" button

sites/public/src/forms/filters/FilterForm.tsx, sites/public/styles/overrides.scss, ui-components/src/locales/ar.json, ui-components/src/locales/bn.json, ui-components/src/locales/es.json, ui-components/src/locales/general.json
- Closes #827
Update the filter modal style to match the update mocks.
=> Update filter modal styling to match the updated mocks

backend/core/src/seeds/listings/listing-detroit-10145.ts, backend/core/src/seeds/listings/listing-detroit-10147.ts, backend/core/src/seeds/listings/listing-detroit-10151.ts, backend/core/src/seeds/listings/listing-detroit-10157.ts, backend/core/src/seeds/listings/listing-detroit-10159.ts, backend/core/src/seeds/listings/listing-detroit-treymore.ts
Update the images for several listings with either photos that more accurately represent the listing (Tara noticed some were obviously wrong) or are higher quality. I also added a few images to ones that were missing an image. 
Reseed your db using the new seed and look at the /listings
=> Update seed listings with more accurate photos

backend/core/src/seeds/listings/listing-detroit-10169.ts
This PR addresses #897
Edits the pending listing to have an application open date in the future and a listing status of active.
If you have one commit and …
=> Edit seeding for pending listing

backend/core/src/migration/1640110170049-seed-detroit-translation-entries.ts, backend/core/src/views/new-listing.hbs, backend/core/src/views/update-listing.hbs
Adds translations for the new listing emails and the reminder to update emails.
=> Add more translations to emails

backend/core/src/shared/email/email.service.ts
We're currently seeing this issue when trying to log into the partner portal:
```
Error: ENOENT: no such file or directory, scandir '/usr/src/app/dist/src/views/partials'
at Object.readdirSync (fs.js:1043:3)
at EmailService.partials (/usr/src/app/dist/src/shared/email/email.service.js:164:22)
at new EmailService (/usr/src/app/dist/src/shared/email/email.service.js:40:28)
at Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:286:19)
at callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:42:41)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:46:9)
at async Injector.loadProvider …
```
=> Gracefully handle email partials not found

sites/public/src/forms/filters/FilterForm.tsx
- Closes #916
Remove the Accessible Features dropdown filter since we now have the boolean filters.
=> Remove accessible features filter

sites/public/tailwind.config.js
- Closes #979
There was an accessibility issue flagged for the primary color in the public site's Tailwind override, this PR updates that to improve contrast.
In issue #979 there are links to a few other issues describing buttons/links/etc. which had the bad contrast, they can be checked if they use the new color now.
=> chore: update primary color in Tailwind override

backend/core/src/auth/authz_policy.csv, backend/core/src/auth/dto/user-create.dto.ts, backend/core/src/auth/dto/user-update.dto.ts, backend/core/src/auth/services/user.service.ts, backend/core/src/listings/listings.service.ts, backend/core/types/src/backend-swagger.ts, sites/partners/src/listings/Aside.tsx
- Closes #1005- [ ] This change is a dependency for another issue
This prevents a user with isPartner role from publishing (backend and frontend) unless the listing is already published. In addition to the AC in the issue, the close button is hidden for all per a conversation with @kathyccheng .
Sign in as a partner user and you should not be able to publish a listing if it is not already published.
=> feat: hides/prevents partner publish

backend/core/src/auth/passport-strategies/jwt.strategy.ts, backend/core/src/migration/1646422264825-addCommunityPrograms.ts, backend/core/src/seeder/seed.ts, backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts, backend/core/src/seeder/seeds/listings/listing-default-seed.ts, sites/partners/pages/listings/[id]/index.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx, sites/partners/src/listings/PaperListingForm/formTypes.ts, sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx, sites/public/page_content/locale_overrides/general.json, sites/public/src/ListingView.tsx, ui-components/src/blocks/InfoCard.tsx, ui-components/src/locales/general.json
- Closes #1003, #1004
This adds programs back to Detroit with some changes to make it work for their use case.
Go to add or edit a listing in partners with Detroit selected as the jurisdiction. You should see the programs as outlined in the AC of #1003. View the listing on the public site and you should see the programs as outlined in the AC of #1004.
=> feat: adds programs to Detroit

backend/core/scripts/import-listings-basic.ts, backend/core/scripts/import-unit-groups.ts
=> fix(backend): import script percentageOfIncomeValue retrieval logic

backend/core/src/auth/controllers/user.controller.ts, backend/core/src/auth/services/user.service.ts, backend/core/src/shared/filters/catch-all-filter.ts, backend/core/types/src/backend-swagger.ts, sites/partners/src/users/FormUserConfirm.tsx, sites/partners/src/users/FormUserManage.tsx, sites/partners/src/users/ReRequestConfirmation.tsx, ui-components/src/locales/general.json
- Closes [#issue](https://github.com/CityOfDetroit/bloom/issues/1045)
This adds a modal on the detroit partner site's confirmation screen. 
So if a user's confirmation token has timed out, they will be prompted via a modal to request a new confirmation token via email. Given that they provide the email for the user
for engineering: 
mark the expiry date of the token in the `createConfirmationToken` function as in the past (instead of +24, use -24)
1: create a user
2: either wait 1 day, or if the token was set to automatically be expired ignore this step
3: follow the confirmation link in the email for that user
4: enter a valid password
5: a modal should pop up when you attempt to confirm account that the token is invalid
6: fill out and submit the email in that modal
7:  a new email …
=> 1045/allows re-request confirmation on partners

backend/core/src/auth/controllers/user.controller.ts, backend/core/src/auth/services/user.service.ts, sites/partners/src/users/FormUserConfirm.tsx, sites/partners/src/users/ReRequestConfirmation.tsx
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …
=> fix: linting fixes

backend/core/src/auth/services/user.service.ts
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …
=> fix: fixes pagination issue on detroit user grid (#1063)

backend/core/src/listings/dto/filter-type-to-field-map.ts, backend/core/src/listings/dto/listing-filter-params.ts, backend/core/src/listings/types/listing-filter-keys-enum.ts, backend/core/src/listings/views/config.ts, backend/core/src/listings/views/view.spec.ts, backend/core/src/shared/query-filter/custom_filters.ts, backend/core/src/shared/query-filter/index.ts, backend/core/types/src/backend-swagger.ts, sites/public/lib/filterUrlLink.tsx, sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/helpers/filters.ts
- Addresses #1015 
Adds `isVerified` filter param and fixes how community programs are queried.
Requires frontend updates
=> feat(backend): update listing filters

sites/partners/pages/index.tsx, sites/public/lib/helpers.tsx, ui-components/src/global/vendor/AgPagination.tsx, ui-components/src/locales/general.json
Closes #1008
- Closes #1008
Updates listing table following instructions from the ticket.
There is an issue with row sorting - sorting is applied only for the current page, there is no option to sort the whole table (all pages). A backend update is needed (similarly to applications endpoint where the parameter sortBy is exist).
- Open the parters portal and sign in
- Check the listing table and make sure that columns are the same as mentioned on the ticket
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any …
=> feat: Update listing table columns

sites/public/lib/hooks.ts, sites/public/pages/index.tsx, sites/public/pages/listings/filtered.tsx, sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/helpers/filters.ts, ui-components/src/icons/Icons.tsx
- Closes #1016
This updates public so that only active listings show. The issue requests to filter out pending, but this works because we've hidden the ability for partners to close listings and don't provide a way to filter active/closed listings.
Boot this up locally and you should only see active listings. Use the filter and the status filter should stay in place.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small …
=> feat: filters to show only active listings

ui-components/src/locales/general.json
- Closes [1071](https://github.com/CityOfDetroit/bloom/issues/1071)
Changes the public side verified tag string
Look at the tag on the image card of a verified listing.
=> fix: change verified string

sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx
- Closes #1080
This was brought over from Bloom core https://github.com/bloom-housing/bloom/pull/2598
=> fix: select programs working with single jurisdiction

backend/core/src/listings/entities/listing.entity.ts, sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx, sites/partners/src/listings/PaperListingDetails/sections/helpers.ts, sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx, ui-components/src/locales/general.json
- Closes [#issue](https://github.com/CityOfDetroit/bloom/issues/1056)
This exposes the leasing agent's company website field on the partners side
Log in to the partner's site as an admin user
go to create a new listing
fill out all the info, including the newly exposed `Company Website` field
save the listing
verify the listing details page on the partner's side expose that information
go in and edit the listing, and verify that the company website info is there and available and its possible to change that info
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet …
=> feat: exposing leasing company website

sites/partners/pages/index.tsx, ui-components/src/global/vendor/AgPagination.tsx
This adds the loading overlay to the partners listing grid.
Boot up partners and go to the main page. If you want to test it with throttling to get a better view of it, build and start partners so you can use the browser's throttling.
If you have one commit and message, squash. …
=> feat: load overlay to partner listings grid

sites/partners/pages/index.tsx, ui-components/src/global/vendor/AgPagination.tsx
Picked from dev https://github.com/CityOfDetroit/bloom/commit/cab71644ea6a0a6ceb76742951e18497d845e764
=> feat: load overlay to partner listings grid (#1116)

backend/core/src/listings/listings.service.ts
This disables the listing status cron job, since Detroit doesn't currently utilize the application process. If we re-enable it for Detroit, we should refactor it, since it currently takes about 1.2 seconds on average to run. If the system has thousands of listings, then that time will increase.
This is hard to test locally, without having it up for an hour. Once it's on dev though, we should see the periodic run of this drop.
- Either explicitly ask a clarifying …
=> feat: disables overdue listings status cron

sites/public/pages/account/edit.tsx, sites/public/pages/create-account.tsx
Closes #1094
- Closes #1094
- Addresses #1094
Removes "email me..." and "text me..." checkboxes and related logic from the signup form. It also fixes form submission by adding `type="submit"` into the submit button.
1. Try to create an account - you shouldn't see subscription checkboxes
2. Log in and open the edit account form - you shouldn't see subscription checkboxes
3. You should be able to save your settings …
=> feat: Remove signup subscription fields

sites/public/lib/helpers.tsx
Closes #1059
- Closes #1059
- Addresses #1059
Adds summary tables into the listing and listing filtered pages.
1. Open the public site and check listing tables
2. Modify data using partners portal and validate values in the tables
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …
=> feat: Add summary tables into the listing

backend/core/src/email/email.service.spec.ts, backend/core/src/email/email.service.ts, backend/core/src/migration/1649709708991-detroit-email-updates.ts, backend/core/src/shared/views/change-email.hbs, backend/core/src/shared/views/register-email.hbs, backend/core/src/views/change-email.hbs
This PR addresses #1119
This feature updates the new user email subject line, copy and footer.
Make sure public .env JURISDICTION is set to Detroit. If you have to change it to Detroit, yarn build. 
Run yarn db:migration:run in backend/core
Go to public site and create a new account
The email you receive should have updated copy the same as that in screenshot (aside from variables):
- Also review the …
=> feat: update email copy

backend/core/src/listings/entities/listing.entity.ts, backend/core/src/listings/types/listing-season-enum.ts, backend/core/src/migration/1649374032458-marketing-season.ts, backend/core/types/src/backend-swagger.ts, sites/partners/pages/listings/[id]/index.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx, sites/partners/src/listings/PaperListingForm/formTypes.ts, sites/partners/src/listings/PaperListingForm/formatters/DatesFormatter.ts, sites/partners/src/listings/PaperListingForm/index.tsx, sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx, sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx, ui-components/src/locales/general.json
- Closes #1075
Adds the frontend pieces in the partners portal listing form to be able to add/change the marketing type, date, and season. Adds the new backend field for the season.
In partners, add / remove / change the three new fields and ensure they save and reload with their values when you reopen the form.
If you …
=> feat: can add a marketing status to a listing in partners

shared-helpers/src/photos.ts, sites/public/lib/HorizontalScrollSection.module.scss, sites/public/lib/helpers.tsx, sites/public/src/ListingView.tsx, sites/public/styles/overrides.scss, ui-components/src/blocks/ImageCard.tsx, ui-components/src/global/AppearanceTypes.ts, ui-components/src/global/text.scss, ui-components/src/page_components/listing/ListingCard.scss, ui-components/src/page_components/listing/ListingCard.tsx, ui-components/src/text/Tag.scss
Uptakes the new listing card on the home page, directory page, and detail page, targeting the release branch.
=> fix: prop updates for uptaking new listing card

ui-components/src/global/vendor/AgPagination.tsx
Adds 100 to the list of page options.
=> feat: add 100 to ag page options

backend/core/src/listings/dto/filter-type-to-field-map.ts, backend/core/src/listings/dto/listing-filter-params.ts, backend/core/src/listings/listings.service.ts, backend/core/src/listings/tests/listings.service.spec.ts, backend/core/src/listings/types/listing-filter-keys-enum.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10145.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10147.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts, backend/core/test/listings/listings.e2e-spec.ts, backend/core/types/src/backend-swagger.ts, sites/partners/lib/hooks.ts, sites/partners/pages/index.tsx, ui-components/src/global/vendor/AgPagination.tsx, ui-components/src/global/vendor/ag_grid.scss, ui-components/src/helpers/filters.ts
This brings over the the AG grid pagination updates from core as well as cherry-picks https://github.com/CityOfDetroit/bloom/commit/7de874c25e98e88864e1a5a047e9dc03d15dd0d9.
=> Pagination hotfix

sites/public/lib/helpers.tsx, sites/public/pages/listings.tsx
- Addresses #1150
Found in the netlify logs - https://app.netlify.com/sites/detroit-public-dev/functions/___netlify-handler - that there was a type error reading unitGroupSummary. This adds checks, which should resolve that.
You can review this at [this preview](https://deploy-preview-1156--detroit-public-dev.netlify.app/). You should be able to view the details of a listing and the preview URL of that listing, where on dev currently you cannot.
- Either explicitly ask …
=> fix: adds check for unitSummaries?.unitGroupSummary on listing

backend/core/scripts/import-listings-basic.ts, backend/core/scripts/import-unit-groups.ts, backend/core/src/property/entities/property.entity.ts, ui-components/index.ts, ui-components/src/blocks/DashBlock.tsx
There were 33 eslint errors in dev, which was causing failed checks in new Detroit PRs. This is a quick fix that removes those eslint errors.
Checkout this branch, run 'yarn eslint' in the command line - there should be no more errors.
If you have one commit and message, squash. If you need each message to be applied, …
=> fix: eslint errors in dev

sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
This is a quick PR to address some eslint errors occurring after merging PR #1155. These errors did not occur until after merging. 
Run lint in bloom. There should be no errors. All of the fields in Add Unit Group (partners, Add Listing) should operate as they were before.
If you have one commit and message, squash. If …
=> style: add void before trigger functions to avoid eslint errors

sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
- Closes #1190
Adds the leasing agent address back to the listing form (copied from core). I could not reproduce the street not showing issue, but I think it was an issue with not being able to edit the leasing agent address.
Add a leasing agent address, ensure it shows on the public listing detail and the partners detail page.
Add a pick/dropoff application with a custom address and pulling from the leasing agent address and ensure the full street shows.
- Either …
=> fix: add leasing agent address field back to listing form

backend/core/src/auth/controllers/auth.controller.ts, backend/core/src/auth/dto/token.dto.ts, backend/core/types/src/backend-swagger.ts
From core https://github.com/bloom-housing/bloom/pull/2703
=> fix: authservice.token data null issue (#2703)

sites/public/lib/helpers.tsx
Closes #1208
- Closes #1208
- Addresses #1208
Fixes tooltips visibility. It should be visible only for AMI icon and "Confirmed" badge, not "Coming Soon".
1. Open partners
2. Update one listing to be verified & coming soon
3. Check listing badge -> should be "coming soon" without a tooltip
4. Update settings to "listing verified" only
5. The tooltip should be visible after hovering on "Confirmed" badge
- Either explicitly ask a clarifying question, request changes, or …
=> fix: Fix tooltip visibility

sites/public/lib/helpers.tsx, sites/public/src/ListingView.tsx, ui-components/src/blocks/ImageCard.scss
- Closes #1192 
This fixes a margin issue on the right-to-left (RTL) layout on this listing page.
Entry Point: http://localhost:3000/listings
1. Click into any listing page in desktop view
2. Switch between English and Arabic and you should see that the paddings / margins around the main image and the Process section are consistent between the two views.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are …
=> style: listing page rtl css changes

sites/public/pages/listings/filtered.tsx, sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/actions/Button.scss, ui-components/src/blocks/ActionBlock.scss, ui-components/src/blocks/ImageCard.tsx, ui-components/src/forms/FieldGroup.tsx, ui-components/src/global/forms.scss, ui-components/src/page_components/listing/ListingCard.tsx, ui-components/src/page_components/listing/ListingsGroup.scss
- Closes #1249
This PR improves user experience of those using RTL layout by making sure margins and padding are consistent in both LTR and RTL layouts. Only CSS changes.
Entry Point: http://localhost:3000/ar/listings
1. Visit Listings page and switch to Arabic language
2. Notice the Accessible and Coming Soon containers have adequate spacing around the icons and text:
3. Click into the Filter popup
4. Notice the Min and Max Rent Inputs have adequate spacing around the prepend and placeholder text, as well as between the Done and Clear buttons:
5. Click into any listing
6. The Coming Soon button is fixed here as well
- Pull the changes down locally and test that the …
=> style: rtl margin and padding fixes

sites/public/lib/helpers.tsx, sites/public/pages/listings/filtered.tsx
- Closes #1245 and #1247
This fixes both of the related issues. #1245 was simple, we were missing the initial array for a reduce. Limit and page handling were also updated.
Either locally or on the public deploy preview, you can test out the pagination updates. For #1245, I don't want you pointing at production data to test.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good …
=> 1245 & 1247 fix page not found and pagination

sites/public/src/forms/filters/FilterForm.tsx, ui-components/src/global/forms.scss
- Closes #1272 
This PR fixes the Min and Max Rent field bugs in the filter form: 1) the fields no longer accept anything except numerical inputs and 2) there is no longer a padding issue when the min > max errors are thrown
Entry Point: http://localhost:3000/listings | https://detroit-public-dev.netlify.app/listings
1. Enter into Filter Form
2. Try to enter non-integers into Min and Max Rent field - you should not be able to
3. Input a min rent larger than the max rent - notice the padding issue is fixed:
- Pull the changes down locally and test that the …
=> fix: min max rent inputs have type number, and padding fix on error

backend/core/src/migration/1652130526521-set-common-app-empty.ts, backend/core/src/seeder/seed.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts, sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx, sites/public/src/ListingView.tsx, ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
- Closes #1244
* Removes the common application question from the partners listing form
* Sets common app to false for all listings
* Opens online application links in a new tab
Ensure the common app question is removed from partners, that you can add/remove a custom app URL, that those links open in a new tab, and that the migration sets any existing common app answers to false.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there …
=> refactor: remove common app question from listing form

sites/public/pages/listing/[id]/[slug].tsx, sites/public/pages/preview/listings/[id].tsx, sites/public/src/ListingView.tsx
- Closes #1278
- Addresses #1278
Adds missing detail page sections.
1. Run partners and fill the "Additional Eligibility Rules" fields in a listing page
2. Open preview and check if these sections exist
=> feat: add sections into listing detail page

sites/public/src/ListingView.tsx
- Closes #1278
- Addresses #1278
https://github.com/CityOfDetroit/bloom/pull/1280 has an issue - there are duplicated sections. This PR removes duplicated eligibility section.
1. Run partners and fill the "Additional Eligibility Rules" fields in a listing page
2. Open preview, check if these sections exist and make sure they're not duplicated
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR …
=> fix: remove duplicated sections

sites/public/layouts/application.tsx
The footer is already removed from dev, but for some reason isn't coming over in a merge.
=> fix: removes exygy footer from main

ui-components/src/global/vendor/AgPagination.tsx
This PR addresses #1269  
Each time the user clicks 'next' or 'previous' when paginating the list of rentals, I added a window.scrollTo() call to ensure that the user starts at the top of each new page.
This can be tested by using browserstack or a personal android device on the public site, clicking 'See all rentals", and then testing pagination.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but …
=> fix: scrollTo fix to pagination

backend/core/scripts/import-regions.ts
This script is used to update neighborhoods and regions per a CSV.
=> Region import update regions script

sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
This PR addresses #1339 by switching the default checked field from the closed waitlist option to the open waitlist option. 
This can be tested on the Detroit partners side by adding a new listing and then clicking 'Add Unit Group. After scrolling down you will see open waitlist is selected by default.  
If you have …
=> fix: changed waitlist status default to open

sites/partners/src/listings/PaperListingForm/index.tsx
- Quick Fix for #1368 
Notice that the tabbing went from: 
to this:
=> fix: corrected string to match JSON

sites/public/pages/index.module.scss, sites/public/styles/listings.scss
- Either explicitly ask a clarifying question, request changes, …
=> refactor: bloop blorp

sites/public/src/ListingView.tsx
This PR addresses #1392
Hides the "rental assistance" section in public.
1. Open the public site
2. Make sure the "rental assistance" section is not visible
- [] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is …
=> refactor: remove rental assistance section

sites/public/src/ListingView.tsx
Hides the "management company" section when there is no data.
1. Open partners portal
2. Fill the "Leasing Agent" section and click preview
3. Make sure the section exists
4. Remove all values from the "Leasing Agent" section and click preview
5. Make sure the section is hidden
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …
=> fix: hide management section if there is no data

sites/public/pages/listings/filtered.tsx, ui-components/src/actions/Button.tsx
This PR addresses #1397 
I removed the IconFillColors.primary default from the Icon component since it conflicts with the default theming that v2 styling sets up.
On Detroit, go to the filtered listings page and hover over the Filter button.
If you have one commit and message, …
=> fix: icon changes color on hover

backend/core/src/listings/views/config.ts, sites/partners/page_content/locale_overrides/general.json, sites/partners/pages/index.tsx
This PR addresses #1341
Adds the "last updated" column.
BACKEND CHANGE NEEDED
Only the frontend part is implemented. From the backend perspective, we need to expose the `updatedAt` property in the listing endpoint. …
=> feat: add the last updated column

sites/public/styles/headers.scss
This PR addresses #1316 
This removed the extraneous padding added to the header.
This can be tested by opening Detroit Public and making sure that the header reflects this change.
If you have one commit and message, squash. If you need each message to be applied, rebase and …
=> fix: removed extra header padding

sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx, ui-components/src/locales/general.json
This PR addresses #1301 
Since error messaging around invalid urls is already implemented, this PR just updates the placeholder based on discussions with @kathyccheng.
This can be tested by going to Detroit Partners, signing in, editing an application, going to the 'Application Process' tab, and emptying the company website field to see the new placeholder.
- Either explicitly ask a clarifying question, request changes, or …
=> fix: added placeholder to field

sites/public/src/ResourceLinkCard.tsx
This PR extends PR #1386 and resolves the short-term feedback on issue #2819. 
This PR corrects the spacing to reflect the Figma (48px -> 32px).
The can be tested by navigating to the Detroit Public /get-assistance page
If you have one commit and message, squash. If you need …
=> fix: card vertical spacing fix

backend/core/scripts/import-listings-basic.ts, backend/core/scripts/import-listings-from-csv.ts, backend/core/scripts/import-realpages-availability-report.ts, backend/core/src/ami-charts/entities/ami-chart.entity.ts, backend/core/src/auth/dto/user-filter-type-to-field-map.ts, backend/core/src/auth/services/user.service.ts, backend/core/src/seeder/detroit-seed.ts, backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts, shared-helpers/index.ts, sites/partners/cypress/integration/listing.spec.ts, sites/partners/lib/hooks.ts, sites/partners/pages/users/index.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx, sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx, sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx, sites/public/package.json, sites/public/pages/about.tsx, ui-components/__tests__/actions/ExpandableContent.test.tsx, ui-components/__tests__/tables/AgTable.test.tsx, ui-components/src/blocks/Tooltip.tsx, ui-components/src/forms/FieldGroup.tsx, ui-components/src/overlays/LoadingOverlay.tsx, ui-components/src/page_components/listing/ContentAccordion.tsx, yarn.lock
This PR addresses #1421 
Functionality copied from bloom core:
- Add filter to the Users page. This allows the filtering of Name, Email, and Listings. At least 3 characters must be typed for filtering to apply
New Functionality:
- Make all of the columns in the users table sortable. 
Other:
- Cleanup some random linting warnings/errors throughout the code
1. Go to the /users page and type into the filter box. Results should be filtered to contain only users that match your filter (either name, email, or listings contain the string)
2. Go to the /users page and sort on each column. Results should sort ascending and descending based on each column.
- Review the code itself from a style point of …
=> feat(users): add filtering and sorting to users

sites/public/lib/helpers.tsx
This adds the commit from #1432 to main so we can have this fixed for the long weekend.
=> fix: missing data in hmi tables #1432

sites/partners/pages/index.tsx
This PR addresses #1450
The partners listings table is not showing the correct verified value. The value appears to be correct on the listing obj because it is showing appropriately on the public site and the listing form, just not in the partners table.
Edit a listing to be verified and ensure the value shows correctly in the partners listing table.
- [x[ My code follows the style guidelines of this project
- Either explicitly …
=> fix: partners table not showing correct verified value

sites/partners/pages/index.tsx
This PR addresses #1450
bug fix for sorting on the column.
=> fix: allow sorting of verified column

backend/core/package.json, package.json, sites/partners/package.json, sites/public/package.json, ui-components/package.json, yarn.lock
- Either explicitly ask a clarifying question, request changes, …
=> chore: standardize the typescript version (#3086)

sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts, sites/partners/src/listings/PaperListingForm/index.tsx
This PR addresses #1489
To clear Neighborhood amenities i had to send `null` when no fields are filled.
Remove existing neighborhood amenities from listing. They should be 'none' in partners listing preview, and should not be visible in public listing.
If you have one commit …
=> 1489/Neighborhood Amenities Partners Bug

backend/core/types/src/backend-swagger.ts, sites/partners/pages/application/[id]/index.tsx, sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
This PR gets the backend-swagger into a better state so that any future client change will not run into unrelated changes
=> fix: update for swagger changes

backend/core/package.json, yarn.lock
Port over from core. Allows Heroku deployments to work
=> fix: upgrade ioredis version

ui-components/src/global/forms.scss
This PR addresses #1474
If i get correctly we use `text-indent` to display over margin in Field. It doesn't transfer good for `rtl` for some reason. So handled it just with padding, shouldn't affect other variants of Field.
Go to /finder switch language to arabic, check if it displays properly. 
If you can think of other `Field`'s that can be affected by that change, also check those 
- Either explicitly ask a clarifying …
=> fix: checkbox in bordered field in arabic

sites/public/page_content/locale_overrides/general.json
This PR addresses #1483
Changed string in public listing view
Go to listing, on right side it should call now "Contact information"
=> feat: change management company to contact information

sites/public/page_content/locale_overrides/ar.json, sites/public/page_content/locale_overrides/bn.json, sites/public/page_content/locale_overrides/es.json, sites/public/page_content/locale_overrides/general.json
This PR addresses #1490
It's update from comment to modify `Contact Information`
it's on side of listing page.
=> feat: change leasing agent contact translations

sites/public/layouts/application.tsx
This PR addresses #3267
Updated feedback from LH indicates that outside of the sr-only h2 to indicate the footer, no other h tags are beneficial to use so this PR removes those unnecessary heading tags.
This can be tested by using inspect element on the page and ensuring that the content of the footer doesn't contain heading tags. 
OR
1. Check your settings to see what your VoiceOver modifier key is: 
2. Go back to the branch running locally
3. Click Command + f5 (voiceover should turn on)
4. Click your voiceover modifier key (in my screenshot it is caps lock) + U
5. Use the left or right arrow key until you locate the Headings Menu
6. Use the down arrow to the headings on the page and their respective levels
7. Ensure it matches the discussed changes above
- Read …
=> fix: remove confusing footer h tags

sites/public/pages/listings.tsx
This PR addresses #3268
This is a partial solution to the issue above. This makes "All rentals" an h2 and also cleans up the approach to not make the entire container a heading (LH mentioned this was a point of confusion).
The other changes will be made in ui-components once Detroit is running off of the UI-C package rather than its own local version.
This can be tested by using a the screen reader utility menu to navigate via headings. You will see from there that all rentals is an h2. 
- Also review the acceptance criteria on the Netlify deploy preview (noting that …
=> fix: corrected heading use on listings page

shared-helpers/src/catchNetworkError.ts, ui-components/src/locales/es.json, ui-components/src/locales/general.json
This PR addresses #1515 
It adds missing translations for password expired
To force this error i changed `69` line in `catchNetworkError` to 
`check401Error(NetworkErrorMessage.PasswordOutdated, error)`
Now passing wrong password will throw password outdated message.
If you …
=> feat: add translations for expired password

detroit-ui-components/src/locales/general.json, sites/public/src/ListingView.tsx
This PR addresses #947 
Added `view on map` label to aria-label, with additional `(opens in new window)`. Changed label from `get direction` to `view on map`
go to listing, focus on view on map link with screen reader on. (there are 2 links on page)
If you have one commit and …
=> feat: add meaningful aria label to view on map link

sites/public/src/pages/create-account.tsx
This PR addresses #1545
Added reader only labels for requested fields. Phone field was handled [separately in UIC](https://github.com/bloom-housing/ui-components/pull/52)
go to sign-up page. Using screen reader focus on re-enter password / email. Reader should start with reading label.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise …
=> fix: add missing screen reader only  labels to fields

sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
There was an issue with reordering the community types on the partner site's paper listing form
This PR addresses [#issue](https://github.com/CityOfDetroit/bloom/issues/1576)
This resolve an issue around how the reordering of the community types field on the partner site's paper listing form works
it seems the structure of the data is slightly different now so this is an update to work with that
Go to the detroit partner site 
go to create a new listing, pick a jurisdiction
add 2 (or more) community types
go to reorder them
this should now work
please also verify that when editing an existing listing this same approach should work
- Pull the …
=> fix: update to community type draggability

detroit-ui-components/src/forms/Field.tsx, sites/public/src/components/finder/FinderRentalCosts.tsx
This PR addresses #1544
It's continuation of the ticket. It adds descriptive label to min / max rent fields in finder.
I tried to recreate behaviour we have in  `/listings` filters. I could use describedBy, but there was too much similar information, so i chose solution with aria-label.
go to `/finder` -> click next till you are on a section with two input fields ( minimum rent, maximum rent).
Using screen reader focus on each field.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in …
=> fix: add aria label to min/max rent fields

detroit-ui-components/src/locales/general.json, detroit-ui-components/src/tables/GroupedTable.tsx, detroit-ui-components/src/tables/StandardTable.tsx, sites/public/src/components/listing/ListingView.tsx, sites/public/src/lib/helpers.tsx
This PR addresses #955 
This PR adds an aria-label to the standardTable props and allows for unique labeling on the listings page along with the listing details view. This will aid users in navigating through the page via the tables.
This can be tested by navigating through the listings page and listing detail page with VO key+arrow navigation. Additionally, test this by using VO key + U and then clicking the right arrow until the list of tables. NOTE: in my experience, it only lists the tables in view and zooming out on the page will reveal the other tables available.
- Pull the changes down locally and test that the acceptance criteria is …
=> fix: add aria label to table

detroit-ui-components/src/locales/ar.json, detroit-ui-components/src/locales/bn.json, detroit-ui-components/src/locales/es.json, detroit-ui-components/src/locales/general.json, sites/public/src/layouts/application.tsx, sites/public/src/md_content/accessibility.md, sites/public/src/pages/accessibility.tsx
This PR addresses #1583 
This PR adds the accessibility statement link to the footer and content to the new /accessibility page. Also, the title is a bit simpler than shown in the document but that decision was approved by product!
This can be tested from the homepage to ensure that the footer linking is correct and then on the /accessibility page to verify the content. …
=> fix: add a11y statement

backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
This PR addresses #1610 
This PR adds a missing line (present in core and hba) which marks when a user last logged in. 
This can be tested by pulling this down locally, reseeding, and then signing in to the partners site with admin@example.com.
Then download the user export and verify that all users have a last logged in time of when the reseed occurred except for the admin@example.com account.
- Either explicitly ask a …
=> fix: lastLoginDate stored

backend/core/src/listings/listings.service.ts
This PR addresses #1596 
This PR saves the verifiedAt date to the listings create function to cover the edge case where a listing is verified upon creation. 
This can be tested by pulling this down locally and creating a listing with the verify listing box checked. After clicking publish, export the listings zip and confirm that the verifiedAt date is in place and correct. …
=> fix: include verifiedAt in listing create

backend/core/src/auth/controllers/user.controller.ts, backend/core/src/auth/passport-strategies/local-mfa.strategy.ts, backend/core/src/auth/services/user-csv-exporter.service.ts, backend/core/src/listings/dto/listings-zip-query-params.ts, backend/core/src/listings/helpers.ts, backend/core/src/listings/listings-csv-exporter.service.ts, backend/core/src/listings/listings.controller.ts, backend/core/src/listings/listings.service.ts, backend/core/src/shared/utils/format-local-date.ts, backend/core/src/units/dto/units-csv-query-params.ts, backend/core/test/lib/format-local-date.spec.ts, backend/core/types/src/backend-swagger.ts, sites/partners/src/lib/hooks.ts
Pulls in the following commits from dev
* 7a7597e5e - fix: include verifiedAt in listing create (#1616) <ColinBuyck>
* ec6666d3d - 1602/export memory improvements (#1614) <ColinBuyck>
* 7f96e2a7a - fix: passing tz as param (#1612) <ColinBuyck>
* bce3a9cb1 - fix: add missing line (#1613) <ColinBuyck>
=> Release: 2023-04-14

sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
This PR addresses #1625 
As stated in #3448 there was an issue with re-rendering. Picked changes from mentioned PR that was applicable in Detroit (as rest seem redundant here).
Go to create / edit listing. Check if errors are applied to fields after publishing. For empty listing it should be jurisdiction and listing name error highlighted.
Try to recreate as many possible errors (as they may appear after filling / checking one field and trying to submit), check if adequate fields will be highlighted
- Also review the acceptance criteria on the Netlify deploy preview …
=> fix: Errors not highlighting fields

shared-helpers/src/styles/forms.scss, shared-helpers/src/styles/tables.scss, sites/public/src/layouts/application.module.scss, sites/public/src/layouts/application.tsx, sites/public/src/pages/index.module.scss, sites/public/src/pages/listings.tsx, sites/public/styles/headers.scss, sites/public/styles/overrides.scss
There is no issue associated here. Without internet on a plane / access to current tickets, I just got bored & made some Arabic layout fixes. You can see [screenshots of each of them](https://docs.google.com/document/d/1xWwdgRkaEtmUfbedLLsYcg4zC7P0eHUfL2QVy7mO3u8/edit?usp=sharing) here.
UIC doesn't support RTL yet so these are overrides.
You can check out the doc to see what changed.
- Either explicitly ask a clarifying …
=> fix: various arabic layout fixes

backend/core/src/shared/query-filter/index.ts, sites/public/src/lib/helpers.tsx, sites/public/src/pages/finder.tsx, sites/public/src/pages/listings.tsx, sites/public/src/pages/listings/filtered.tsx
Pulls over the following two commits from dev:
* fb5f3de05 - fix: format currency before filter form submit (#1635)  <Krzysztof Zięcina>
* 761b31f8a - fix: flip min rent with max rent (#1634)  <Krzysztof Zięcina>
=> Release: 2023-08-16

backend/core/src/auth/services/user.service.ts
Pulls over the fix from HBA into doorway to prevent invalid characters in our user accounts. This is the first step of several to prevent email phishing attacks using our emails
On the public site when trying to create a user add a url to the first or last name. You should get an error when submitting it
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small …
=> fix: add character validation on user creation

backend/core/src/auth/services/user.service.ts
Pulls over the latest commit from dev to the main branch
=> fix: add character validation on user creation (#1653)

shared-helpers/src/regions.ts
This PR addresses #1664  
Adding the two broken images on the home page.
I've uploaded the provided images to our Cloudinary so that we have control over the image urls.
Note: I didn't do the same for the two working images, but I could be convinced to do so
On the [home page](http://localhost:3000/) all four of the images for "regions" section should load properly
- Either explicitly ask a clarifying question, request changes, …
=> fix: update region image urls

shared-helpers/src/locales/ar.json, shared-helpers/src/locales/bn.json, shared-helpers/src/locales/es.json, shared-helpers/src/locales/general.json, shared-helpers/src/styles/app-css.scss
This PR is a follow-up to #5198
Updates the css styling since the tailwind isn't loading as expected on the deployed partner's site.
This issue can't be seen locally so check the deploy preview to verify it works
If you have one commit and message, squash. If you need each …
=> fix: remove tailwind
